import DerridaRetaux
import DerridaRetaux.Audit.ArchitectureCounterexample

/-! Generated union of current manuscript correspondence declarations. -/

set_option pp.universes true
set_option pp.explicit false

#check DerridaRetaux.Audit.deterministicCriticalClassification_without_arity_is_false
#print axioms DerridaRetaux.Audit.deterministicCriticalClassification_without_arity_is_false
#check DerridaRetaux.Critical
#print axioms DerridaRetaux.Critical
#check DerridaRetaux.FixedArity.arrivalMomentTail
#print axioms DerridaRetaux.FixedArity.arrivalMomentTail
#check DerridaRetaux.FixedArity.arrivalRecursion
#print axioms DerridaRetaux.FixedArity.arrivalRecursion
#check DerridaRetaux.FixedArity.cubicMoment
#print axioms DerridaRetaux.FixedArity.cubicMoment
#check DerridaRetaux.FixedArity.cubicWeightedChain
#print axioms DerridaRetaux.FixedArity.cubicWeightedChain
#check DerridaRetaux.FixedArity.cubicWeightedInfiniteChain
#print axioms DerridaRetaux.FixedArity.cubicWeightedInfiniteChain
#check DerridaRetaux.FixedArity.farArrivalBoundUniform
#print axioms DerridaRetaux.FixedArity.farArrivalBoundUniform
#check DerridaRetaux.FixedArity.firstTiltedAtomTail
#print axioms DerridaRetaux.FixedArity.firstTiltedAtomTail
#check DerridaRetaux.FixedArity.identifySubsequentialLimit
#print axioms DerridaRetaux.FixedArity.identifySubsequentialLimit
#check DerridaRetaux.FixedArity.momentLaplaceLocalIntegralDerivatives
#print axioms DerridaRetaux.FixedArity.momentLaplaceLocalIntegralDerivatives
#check DerridaRetaux.FixedArity.momentLaplaceODE
#print axioms DerridaRetaux.FixedArity.momentLaplaceODE
#check DerridaRetaux.FixedArity.pointwiseBound
#print axioms DerridaRetaux.FixedArity.pointwiseBound
#check DerridaRetaux.FixedArity.productAsymptoticOfSurvival
#print axioms DerridaRetaux.FixedArity.productAsymptoticOfSurvival
#check DerridaRetaux.FixedArity.profile
#print axioms DerridaRetaux.FixedArity.profile
#check DerridaRetaux.FixedArity.profileDensity
#print axioms DerridaRetaux.FixedArity.profileDensity
#check DerridaRetaux.FixedArity.sharpness
#print axioms DerridaRetaux.FixedArity.sharpness
#check DerridaRetaux.FixedArity.sharpnessSurvival
#print axioms DerridaRetaux.FixedArity.sharpnessSurvival
#check DerridaRetaux.FixedArity.sharpness_core
#print axioms DerridaRetaux.FixedArity.sharpness_core
#check DerridaRetaux.FixedArity.smoothing
#print axioms DerridaRetaux.FixedArity.smoothing
#check DerridaRetaux.FixedArity.smoothingTwoParameter
#print axioms DerridaRetaux.FixedArity.smoothingTwoParameter
#check DerridaRetaux.FixedArity.sourceDifference
#print axioms DerridaRetaux.FixedArity.sourceDifference
#check DerridaRetaux.FixedArity.subsequentialConstructedString_cumulative_eq_model
#print axioms DerridaRetaux.FixedArity.subsequentialConstructedString_cumulative_eq_model
#check DerridaRetaux.FixedArity.subsequentialConstructedString_hasSingularCharacteristic
#print axioms DerridaRetaux.FixedArity.subsequentialConstructedString_hasSingularCharacteristic
#check DerridaRetaux.FixedArity.subsequentialDensity_eq_yaglom
#print axioms DerridaRetaux.FixedArity.subsequentialDensity_eq_yaglom
#check DerridaRetaux.FixedArity.subsequentialHasWeakEquationOn
#print axioms DerridaRetaux.FixedArity.subsequentialHasWeakEquationOn
#check DerridaRetaux.FixedArity.subsequentialLimitProperties
#print axioms DerridaRetaux.FixedArity.subsequentialLimitProperties
#check DerridaRetaux.FixedArity.subsequentialMildEquation
#print axioms DerridaRetaux.FixedArity.subsequentialMildEquation
#check DerridaRetaux.FixedArity.subsequentialMoment_bounds
#print axioms DerridaRetaux.FixedArity.subsequentialMoment_bounds
#check DerridaRetaux.FixedArity.subsequentialMoment_tendsto
#print axioms DerridaRetaux.FixedArity.subsequentialMoment_tendsto
#check DerridaRetaux.FixedArity.subsequentialThirdMomentTail
#print axioms DerridaRetaux.FixedArity.subsequentialThirdMomentTail
#check DerridaRetaux.FixedArity.subsequential_physicalTime_identification
#print axioms DerridaRetaux.FixedArity.subsequential_physicalTime_identification
#check DerridaRetaux.FixedArity.thirdMomentTail
#print axioms DerridaRetaux.FixedArity.thirdMomentTail
#check DerridaRetaux.FixedArity.thirdOrderTaylorRemainder
#print axioms DerridaRetaux.FixedArity.thirdOrderTaylorRemainder
#check DerridaRetaux.FixedArity.tiltedLawRecursion
#print axioms DerridaRetaux.FixedArity.tiltedLawRecursion
#check DerridaRetaux.FixedArity.weightedMass
#print axioms DerridaRetaux.FixedArity.weightedMass
#check DerridaRetaux.HasIntegralDerivativeOn
#print axioms DerridaRetaux.HasIntegralDerivativeOn
#check DerridaRetaux.HasIntegralDerivativeOn.contDiffOn_Ioo_of_continuousOn_Icc
#print axioms DerridaRetaux.HasIntegralDerivativeOn.contDiffOn_Ioo_of_continuousOn_Icc
#check DerridaRetaux.HasIntegralDerivativeOn.hasDerivAt_of_continuousOn_Icc
#print axioms DerridaRetaux.HasIntegralDerivativeOn.hasDerivAt_of_continuousOn_Icc
#check DerridaRetaux.HasSingularCharacteristic
#print axioms DerridaRetaux.HasSingularCharacteristic
#check DerridaRetaux.IsEntranceNormalizedVolterraSolution
#print axioms DerridaRetaux.IsEntranceNormalizedVolterraSolution
#check DerridaRetaux.ProfileInitialData
#print axioms DerridaRetaux.ProfileInitialData
#check DerridaRetaux.SourceMonomialTag
#print axioms DerridaRetaux.SourceMonomialTag
#check DerridaRetaux.SourceMonomialTag.Valid
#print axioms DerridaRetaux.SourceMonomialTag.Valid
#check DerridaRetaux.SourceMonomialTag.e_le_arity_product
#print axioms DerridaRetaux.SourceMonomialTag.e_le_arity_product
#check DerridaRetaux.SourceMonomialTag.q_add_w_ge_two_of_w_pos
#print axioms DerridaRetaux.SourceMonomialTag.q_add_w_ge_two_of_w_pos
#check DerridaRetaux.SourceMonomialTag.q_eq_outerDegree_sub_nB_add_e_of_function
#print axioms DerridaRetaux.SourceMonomialTag.q_eq_outerDegree_sub_nB_add_e_of_function
#check DerridaRetaux.SourceMonomialTag.q_eq_zero_only_allBoundary
#print axioms DerridaRetaux.SourceMonomialTag.q_eq_zero_only_allBoundary
#check DerridaRetaux.SourceMonomialTag.q_ge_three_of_w_eq_zero
#print axioms DerridaRetaux.SourceMonomialTag.q_ge_three_of_w_eq_zero
#check DerridaRetaux.SourceMonomialTag.q_le_arity_sq
#print axioms DerridaRetaux.SourceMonomialTag.q_le_arity_sq
#check DerridaRetaux.SourceMonomialTag.residualExponent_le_two_of_w_pos
#print axioms DerridaRetaux.SourceMonomialTag.residualExponent_le_two_of_w_pos
#check DerridaRetaux.SourceMonomialTag.tailThreshold_eq
#print axioms DerridaRetaux.SourceMonomialTag.tailThreshold_eq
#check DerridaRetaux.SourceMonomialTag.tailThreshold_twice_gt
#print axioms DerridaRetaux.SourceMonomialTag.tailThreshold_twice_gt
#check DerridaRetaux.SourceMonomialTag.valid_branch_trichotomy
#print axioms DerridaRetaux.SourceMonomialTag.valid_branch_trichotomy
#check DerridaRetaux.TendstoInL1On
#print axioms DerridaRetaux.TendstoInL1On
#check DerridaRetaux.WeightedSupThreeLE
#print axioms DerridaRetaux.WeightedSupThreeLE
#check DerridaRetaux.abs_convex_pair_le
#print axioms DerridaRetaux.abs_convex_pair_le
#check DerridaRetaux.abs_gridBilinearInterp_sub_le_of_node_modulus
#print axioms DerridaRetaux.abs_gridBilinearInterp_sub_le_of_node_modulus
#check DerridaRetaux.abs_gridBilinearInterp_sub_lowerLeft_le
#print axioms DerridaRetaux.abs_gridBilinearInterp_sub_lowerLeft_le
#check DerridaRetaux.abs_normalizedIntegratedExpThirdRemainder_le_sqrt
#print axioms DerridaRetaux.abs_normalizedIntegratedExpThirdRemainder_le_sqrt
#check DerridaRetaux.actual_sourceDifference_terms_have_valid_normalForms
#print axioms DerridaRetaux.actual_sourceDifference_terms_have_valid_normalForms
#check DerridaRetaux.ae_eq_of_halfLine_laplace_eq
#print axioms DerridaRetaux.ae_eq_of_halfLine_laplace_eq
#check DerridaRetaux.antitone_transportProduct
#print axioms DerridaRetaux.antitone_transportProduct
#check DerridaRetaux.arity_mul_survival_le_tiltedPositive
#print axioms DerridaRetaux.arity_mul_survival_le_tiltedPositive
#check DerridaRetaux.arrivalAlpha
#print axioms DerridaRetaux.arrivalAlpha
#check DerridaRetaux.arrivalCoeff_duhamel
#print axioms DerridaRetaux.arrivalCoeff_duhamel
#check DerridaRetaux.arrivalCoeff_far_bound_of_H1
#print axioms DerridaRetaux.arrivalCoeff_far_bound_of_H1
#check DerridaRetaux.arrivalCoeff_scaled_far_constant_of_H1
#print axioms DerridaRetaux.arrivalCoeff_scaled_far_constant_of_H1
#check DerridaRetaux.arrivalCoeff_succ_eq_formulaSource
#print axioms DerridaRetaux.arrivalCoeff_succ_eq_formulaSource
#check DerridaRetaux.arrivalDenom_mul_product_succ
#print axioms DerridaRetaux.arrivalDenom_mul_product_succ
#check DerridaRetaux.arrivalFormulaSource
#print axioms DerridaRetaux.arrivalFormulaSource
#check DerridaRetaux.arrivalFormulaSource_block_le_initialTail_add_difference
#print axioms DerridaRetaux.arrivalFormulaSource_block_le_initialTail_add_difference
#check DerridaRetaux.arrivalFormulaSource_nonneg
#print axioms DerridaRetaux.arrivalFormulaSource_nonneg
#check DerridaRetaux.arrivalFormulaSource_sub_eq_fullyExpanded
#print axioms DerridaRetaux.arrivalFormulaSource_sub_eq_fullyExpanded
#check DerridaRetaux.arrivalFormulaSource_sub_eq_threeChanges
#print axioms DerridaRetaux.arrivalFormulaSource_sub_eq_threeChanges
#check DerridaRetaux.arrivalFormulaSource_sub_tail_bound_of_H1
#print axioms DerridaRetaux.arrivalFormulaSource_sub_tail_bound_of_H1
#check DerridaRetaux.arrivalFormulaSource_term_eq_zero
#print axioms DerridaRetaux.arrivalFormulaSource_term_eq_zero
#check DerridaRetaux.arrivalInitialBlock_le_coefficientTail_of_cubic
#print axioms DerridaRetaux.arrivalInitialBlock_le_coefficientTail_of_cubic
#check DerridaRetaux.arrivalInitialIndex_injective
#print axioms DerridaRetaux.arrivalInitialIndex_injective
#check DerridaRetaux.arrivalKappa_succ
#print axioms DerridaRetaux.arrivalKappa_succ
#check DerridaRetaux.arrivalMomentTail_bounds
#print axioms DerridaRetaux.arrivalMomentTail_bounds
#check DerridaRetaux.arrivalValueAtOne
#print axioms DerridaRetaux.arrivalValueAtOne
#check DerridaRetaux.bilinearInterp_space_cell_bound
#print axioms DerridaRetaux.bilinearInterp_space_cell_bound
#check DerridaRetaux.bilinearInterp_time_cell_bound
#print axioms DerridaRetaux.bilinearInterp_time_cell_bound
#check DerridaRetaux.bilinearInterp_transpose
#print axioms DerridaRetaux.bilinearInterp_transpose
#check DerridaRetaux.coefficientTail_le_shiftedCubicMoment_div
#print axioms DerridaRetaux.coefficientTail_le_shiftedCubicMoment_div
#check DerridaRetaux.coefficientVariation_orbit_of_H1a_and_pointwise
#print axioms DerridaRetaux.coefficientVariation_orbit_of_H1a_and_pointwise
#check DerridaRetaux.compact_lattice_sums_tendsto_of_locallyUniform
#print axioms DerridaRetaux.compact_lattice_sums_tendsto_of_locallyUniform
#check DerridaRetaux.conditionalFirstMoment_tendsto
#print axioms DerridaRetaux.conditionalFirstMoment_tendsto
#check DerridaRetaux.conditionalPositiveL1Error_eq_two_mul_totalVariation
#print axioms DerridaRetaux.conditionalPositiveL1Error_eq_two_mul_totalVariation
#check DerridaRetaux.conditionalPositiveL1Error_le
#print axioms DerridaRetaux.conditionalPositiveL1Error_le
#check DerridaRetaux.conditionalPositiveMass_eq_normalizedReadoutMass
#print axioms DerridaRetaux.conditionalPositiveMass_eq_normalizedReadoutMass
#check DerridaRetaux.constructedEndpointAtTime
#print axioms DerridaRetaux.constructedEndpointAtTime
#check DerridaRetaux.constructedEndpointSlope
#print axioms DerridaRetaux.constructedEndpointSlope
#check DerridaRetaux.constructedEndpointSolution
#print axioms DerridaRetaux.constructedEndpointSolution
#check DerridaRetaux.constructedEndpointSolution_pos_of_neg
#print axioms DerridaRetaux.constructedEndpointSolution_pos_of_neg
#check DerridaRetaux.constructedEntranceString_correctRightEnd
#print axioms DerridaRetaux.constructedEntranceString_correctRightEnd
#check DerridaRetaux.constructedEntranceString_hasRightEnd_zero
#print axioms DerridaRetaux.constructedEntranceString_hasRightEnd_zero
#check DerridaRetaux.constructedEntranceString_hasSecondEntranceMoment
#print axioms DerridaRetaux.constructedEntranceString_hasSecondEntranceMoment
#check DerridaRetaux.constructedEntranceString_hasSingularCharacteristic
#print axioms DerridaRetaux.constructedEntranceString_hasSingularCharacteristic
#check DerridaRetaux.constructedEntranceString_hasSingularCharacteristic_of_representation
#print axioms DerridaRetaux.constructedEntranceString_hasSingularCharacteristic_of_representation
#check DerridaRetaux.constructedEntranceString_isEntranceType
#print axioms DerridaRetaux.constructedEntranceString_isEntranceType
#check DerridaRetaux.constructedPhi
#print axioms DerridaRetaux.constructedPhi
#check DerridaRetaux.constructed_stringCumulative_of_nonneg
#print axioms DerridaRetaux.constructed_stringCumulative_of_nonneg
#check DerridaRetaux.continuous_density_eq_of_halfLine_laplace_eq
#print axioms DerridaRetaux.continuous_density_eq_of_halfLine_laplace_eq
#check DerridaRetaux.conv
#print axioms DerridaRetaux.conv
#check DerridaRetaux.conv_shiftLeft_conv_self
#print axioms DerridaRetaux.conv_shiftLeft_conv_self
#check DerridaRetaux.conv_shiftLeft_self
#print axioms DerridaRetaux.conv_shiftLeft_self
#check DerridaRetaux.convolutionNorms_orbit_of_pointwise
#print axioms DerridaRetaux.convolutionNorms_orbit_of_pointwise
#check DerridaRetaux.countable_diagonal_subsequence
#print axioms DerridaRetaux.countable_diagonal_subsequence
#check DerridaRetaux.criticalProduct_bound_all_of_CDHLSProductFact
#print axioms DerridaRetaux.criticalProduct_bound_all_of_CDHLSProductFact
#check DerridaRetaux.criticalProduct_log_limit_of_survival
#print axioms DerridaRetaux.criticalProduct_log_limit_of_survival
#check DerridaRetaux.critical_drStep
#print axioms DerridaRetaux.critical_drStep
#check DerridaRetaux.critical_isDirac_eq_binary
#print axioms DerridaRetaux.critical_isDirac_eq_binary
#check DerridaRetaux.cubicAllocationIncrementMass_hasSum
#print axioms DerridaRetaux.cubicAllocationIncrementMass_hasSum
#check DerridaRetaux.cubicAllocationOutputPMF_apply_toReal
#print axioms DerridaRetaux.cubicAllocationOutputPMF_apply_toReal
#check DerridaRetaux.cubicAllocationPMF
#print axioms DerridaRetaux.cubicAllocationPMF
#check DerridaRetaux.cubicAllocationWeight
#print axioms DerridaRetaux.cubicAllocationWeight
#check DerridaRetaux.cubicAllocationWeight_hasSum_one
#print axioms DerridaRetaux.cubicAllocationWeight_hasSum_one
#check DerridaRetaux.cubicAllocation_carrier_identity
#print axioms DerridaRetaux.cubicAllocation_carrier_identity
#check DerridaRetaux.cubicAllocation_hasSum
#print axioms DerridaRetaux.cubicAllocation_hasSum
#check DerridaRetaux.cubicCarrier_eq_fallingFactorials
#print axioms DerridaRetaux.cubicCarrier_eq_fallingFactorials
#check DerridaRetaux.cubicCarrier_natPred
#print axioms DerridaRetaux.cubicCarrier_natPred
#check DerridaRetaux.cubicCarrier_pos_iff_of_three_le
#print axioms DerridaRetaux.cubicCarrier_pos_iff_of_three_le
#check DerridaRetaux.cubicCarrier_two
#print axioms DerridaRetaux.cubicCarrier_two
#check DerridaRetaux.cubicSizeBiasedLaw
#print axioms DerridaRetaux.cubicSizeBiasedLaw
#check DerridaRetaux.cubicSizeBiasedPMF_bind_cubicSpineKernel
#print axioms DerridaRetaux.cubicSizeBiasedPMF_bind_cubicSpineKernel
#check DerridaRetaux.cubicSpineExpectedPositiveIncrement_eq_ratio
#print axioms DerridaRetaux.cubicSpineExpectedPositiveIncrement_eq_ratio
#check DerridaRetaux.cubicSpineExpectedPositiveIncrement_le_four
#print axioms DerridaRetaux.cubicSpineExpectedPositiveIncrement_le_four
#check DerridaRetaux.cubicSpineKernel
#print axioms DerridaRetaux.cubicSpineKernel
#check DerridaRetaux.cubicSpineKernel_eq_allocation
#print axioms DerridaRetaux.cubicSpineKernel_eq_allocation
#check DerridaRetaux.cubicSpineKernel_eq_pure_zero_of_carrier_eq_zero
#print axioms DerridaRetaux.cubicSpineKernel_eq_pure_zero_of_carrier_eq_zero
#check DerridaRetaux.cubicSpineKernel_two_one
#print axioms DerridaRetaux.cubicSpineKernel_two_one
#check DerridaRetaux.cubicSpineOutput
#print axioms DerridaRetaux.cubicSpineOutput
#check DerridaRetaux.cubicTailIntegrand_lowerSemicontinuous
#print axioms DerridaRetaux.cubicTailIntegrand_lowerSemicontinuous
#check DerridaRetaux.cubicWeight
#print axioms DerridaRetaux.cubicWeight
#check DerridaRetaux.cubicWeight_add_le_mul
#print axioms DerridaRetaux.cubicWeight_add_le_mul
#check DerridaRetaux.decrement_tendsto_of_exact_identity
#print axioms DerridaRetaux.decrement_tendsto_of_exact_identity
#check DerridaRetaux.densityB
#print axioms DerridaRetaux.densityB
#check DerridaRetaux.densityB_orbit_succ
#print axioms DerridaRetaux.densityB_orbit_succ
#check DerridaRetaux.densityCoeff_nonneg_and_le_choose
#print axioms DerridaRetaux.densityCoeff_nonneg_and_le_choose
#check DerridaRetaux.densityE_orbit_weightedL1_order_three
#print axioms DerridaRetaux.densityE_orbit_weightedL1_order_three
#check DerridaRetaux.densityE_orbit_weightedSup_order_four
#print axioms DerridaRetaux.densityE_orbit_weightedSup_order_four
#check DerridaRetaux.densityE_two
#print axioms DerridaRetaux.densityE_two
#check DerridaRetaux.densityHigherSegment_orbit_scaled_tendsto_zero_on_annulus
#print axioms DerridaRetaux.densityHigherSegment_orbit_scaled_tendsto_zero_on_annulus
#check DerridaRetaux.densityHigherSegment_scaled_abs_le_const_div
#print axioms DerridaRetaux.densityHigherSegment_scaled_abs_le_const_div
#check DerridaRetaux.densityHigherSegment_scaled_tendsto_zero_of_order_four_on_annulus
#print axioms DerridaRetaux.densityHigherSegment_scaled_tendsto_zero_of_order_four_on_annulus
#check DerridaRetaux.densityHigherSegment_supLE_of_orbit_bounds
#print axioms DerridaRetaux.densityHigherSegment_supLE_of_orbit_bounds
#check DerridaRetaux.densityHigherSegment_supLE_of_order_four
#print axioms DerridaRetaux.densityHigherSegment_supLE_of_order_four
#check DerridaRetaux.densityInitialSegment_weightedSup_bound
#print axioms DerridaRetaux.densityInitialSegment_weightedSup_bound
#check DerridaRetaux.densityLateSegment
#print axioms DerridaRetaux.densityLateSegment
#check DerridaRetaux.densityLateSegment_derivative_weightedSup_log_bound
#print axioms DerridaRetaux.densityLateSegment_derivative_weightedSup_log_bound
#check DerridaRetaux.densityNonlinearSource_orbit_le_of_weightedL1
#print axioms DerridaRetaux.densityNonlinearSource_orbit_le_of_weightedL1
#check DerridaRetaux.densityProfilePrefixL1Error_linearCutoff_tendsto_zero_of_compact
#print axioms DerridaRetaux.densityProfilePrefixL1Error_linearCutoff_tendsto_zero_of_compact
#check DerridaRetaux.densityQuadraticKernel_succ
#print axioms DerridaRetaux.densityQuadraticKernel_succ
#check DerridaRetaux.densityQuadraticSegment_derivative_weightedSup_log_bound
#print axioms DerridaRetaux.densityQuadraticSegment_derivative_weightedSup_log_bound
#check DerridaRetaux.densityQuadraticSegment_eq_weightedKernelSum
#print axioms DerridaRetaux.densityQuadraticSegment_eq_weightedKernelSum
#check DerridaRetaux.densityR
#print axioms DerridaRetaux.densityR
#check DerridaRetaux.densityR_apply
#print axioms DerridaRetaux.densityR_apply
#check DerridaRetaux.densityR_orbit_weightedSup_order_four
#print axioms DerridaRetaux.densityR_orbit_weightedSup_order_four
#check DerridaRetaux.densityR_two
#print axioms DerridaRetaux.densityR_two
#check DerridaRetaux.densityRhoSource
#print axioms DerridaRetaux.densityRhoSource
#check DerridaRetaux.deriv_momentLaplaceGap_eq
#print axioms DerridaRetaux.deriv_momentLaplaceGap_eq
#check DerridaRetaux.discreteDerivative
#print axioms DerridaRetaux.discreteDerivative
#check DerridaRetaux.discreteDerivative_densityQuadraticSegment_telescope
#print axioms DerridaRetaux.discreteDerivative_densityQuadraticSegment_telescope
#check DerridaRetaux.discreteL1Distance_eq_two_mul_discreteTotalVariation
#print axioms DerridaRetaux.discreteL1Distance_eq_two_mul_discreteTotalVariation
#check DerridaRetaux.drStepProb
#print axioms DerridaRetaux.drStepProb
#check DerridaRetaux.drStep_eq_drStepProb
#print axioms DerridaRetaux.drStep_eq_drStepProb
#check DerridaRetaux.drStep_two_diracMass_one
#print axioms DerridaRetaux.drStep_two_diracMass_one
#check DerridaRetaux.endpointEntrance_wronskian
#print axioms DerridaRetaux.endpointEntrance_wronskian
#check DerridaRetaux.endpoint_reduction_representation
#print axioms DerridaRetaux.endpoint_reduction_representation
#check DerridaRetaux.entranceSolutionFromEndpoint
#print axioms DerridaRetaux.entranceSolutionFromEndpoint
#check DerridaRetaux.entranceSolutionFromEndpoint_isVolterra_constructedString
#print axioms DerridaRetaux.entranceSolutionFromEndpoint_isVolterra_constructedString
#check DerridaRetaux.entranceSolutionFromEndpoint_pos
#print axioms DerridaRetaux.entranceSolutionFromEndpoint_pos
#check DerridaRetaux.excess
#print axioms DerridaRetaux.excess
#check DerridaRetaux.excessRecursionMap
#print axioms DerridaRetaux.excessRecursionMap
#check DerridaRetaux.excessRecursionMap_barrier_tendsto
#print axioms DerridaRetaux.excessRecursionMap_barrier_tendsto
#check DerridaRetaux.excessRecursionMap_sub_ge
#print axioms DerridaRetaux.excessRecursionMap_sub_ge
#check DerridaRetaux.excess_orbit_decrement
#print axioms DerridaRetaux.excess_orbit_decrement
#check DerridaRetaux.excess_orbit_decrement_tendsto
#print axioms DerridaRetaux.excess_orbit_decrement_tendsto
#check DerridaRetaux.excess_orbit_recursionMap
#print axioms DerridaRetaux.excess_orbit_recursionMap
#check DerridaRetaux.excess_tendsto_of_survival_asymptotic
#print axioms DerridaRetaux.excess_tendsto_of_survival_asymptotic
#check DerridaRetaux.exhaustionLimits_compatible
#print axioms DerridaRetaux.exhaustionLimits_compatible
#check DerridaRetaux.exists_gridBilinearInterp_diagonal_subsequence
#print axioms DerridaRetaux.exists_gridBilinearInterp_diagonal_subsequence
#check DerridaRetaux.exists_mass_ge_two_of_critical_two_not_fixed
#print axioms DerridaRetaux.exists_mass_ge_two_of_critical_two_not_fixed
#check DerridaRetaux.exists_orbitScaledGrid_diagonal_subsequence_and_readout
#print axioms DerridaRetaux.exists_orbitScaledGrid_diagonal_subsequence_and_readout
#check DerridaRetaux.expThirdRemainder_bounds
#print axioms DerridaRetaux.expThirdRemainder_bounds
#check DerridaRetaux.exponentialProfileGrid_tsum_tendsto_two
#print axioms DerridaRetaux.exponentialProfileGrid_tsum_tendsto_two
#check DerridaRetaux.finiteMeasure_eq_of_halfLine_laplace_eq
#print axioms DerridaRetaux.finiteMeasure_eq_of_halfLine_laplace_eq
#check DerridaRetaux.finiteThirdMoment_implies_cubic_tail_limits
#print axioms DerridaRetaux.finiteThirdMoment_implies_cubic_tail_limits
#check DerridaRetaux.firstTiltedAtomTail_bound_all
#print axioms DerridaRetaux.firstTiltedAtomTail_bound_all
#check DerridaRetaux.firstTiltedAtomTail_eq_atom_add_succ
#print axioms DerridaRetaux.firstTiltedAtomTail_eq_atom_add_succ
#check DerridaRetaux.firstTiltedAtom_eq_theta_sub_theta_succ_add
#print axioms DerridaRetaux.firstTiltedAtom_eq_theta_sub_theta_succ_add
#check DerridaRetaux.firstTiltedAtom_squareWeight_sum_eq
#print axioms DerridaRetaux.firstTiltedAtom_squareWeight_sum_eq
#check DerridaRetaux.firstTiltedAtom_squareWeight_sum_linear_bound
#print axioms DerridaRetaux.firstTiltedAtom_squareWeight_sum_linear_bound
#check DerridaRetaux.fixedAtom_tendsto_of_compact_profile_error
#print axioms DerridaRetaux.fixedAtom_tendsto_of_compact_profile_error
#check DerridaRetaux.generatingFunction_drStep
#print axioms DerridaRetaux.generatingFunction_drStep
#check DerridaRetaux.generatingFunction_drStep_cross
#print axioms DerridaRetaux.generatingFunction_drStep_cross
#check DerridaRetaux.generatingFunction_orbit_succ_cross
#print axioms DerridaRetaux.generatingFunction_orbit_succ_cross
#check DerridaRetaux.generatingFunction_paperStep
#print axioms DerridaRetaux.generatingFunction_paperStep
#check DerridaRetaux.geometricReadout_sub_boundary_le
#print axioms DerridaRetaux.geometricReadout_sub_boundary_le
#check DerridaRetaux.gluedExhaustionLimit_mild_of_H1a
#print axioms DerridaRetaux.gluedExhaustionLimit_mild_of_H1a
#check DerridaRetaux.gridBilinearInterp
#print axioms DerridaRetaux.gridBilinearInterp
#check DerridaRetaux.gridBilinearInterp_eq_four_weights
#print axioms DerridaRetaux.gridBilinearInterp_eq_four_weights
#check DerridaRetaux.gridBilinearInterp_family_equicontinuousOn_of_eventually
#print axioms DerridaRetaux.gridBilinearInterp_family_equicontinuousOn_of_eventually
#check DerridaRetaux.gridBilinearInterp_family_eventuallyEquicontinuousOn_rectangle
#print axioms DerridaRetaux.gridBilinearInterp_family_eventuallyEquicontinuousOn_rectangle
#check DerridaRetaux.gridBilinearInterp_family_uniformlyBoundedOn_rectangle
#print axioms DerridaRetaux.gridBilinearInterp_family_uniformlyBoundedOn_rectangle
#check DerridaRetaux.gridBilinearInterp_space_cell_bound
#print axioms DerridaRetaux.gridBilinearInterp_space_cell_bound
#check DerridaRetaux.gridBilinearInterp_time_cell_bound
#print axioms DerridaRetaux.gridBilinearInterp_time_cell_bound
#check DerridaRetaux.gridTimeArraySum_tendsto_of_uniform_approximation_on_Ioi
#print axioms DerridaRetaux.gridTimeArraySum_tendsto_of_uniform_approximation_on_Ioi
#check DerridaRetaux.hasDerivAt_constructedEndpointAtTime
#print axioms DerridaRetaux.hasDerivAt_constructedEndpointAtTime
#check DerridaRetaux.hasDerivAt_constructedEndpointSolution_of_neg
#print axioms DerridaRetaux.hasDerivAt_constructedEndpointSolution_of_neg
#check DerridaRetaux.hasDerivAt_constructedPhi
#print axioms DerridaRetaux.hasDerivAt_constructedPhi
#check DerridaRetaux.hasDerivAt_entranceSolutionFromEndpoint
#print axioms DerridaRetaux.hasDerivAt_entranceSolutionFromEndpoint
#check DerridaRetaux.hasDerivAt_entranceSolutionFromEndpointSlope
#print axioms DerridaRetaux.hasDerivAt_entranceSolutionFromEndpointSlope
#check DerridaRetaux.hasDerivAt_momentLaplaceGap
#print axioms DerridaRetaux.hasDerivAt_momentLaplaceGap
#check DerridaRetaux.hasDerivAt_stringA2Y
#print axioms DerridaRetaux.hasDerivAt_stringA2Y
#check DerridaRetaux.hasDerivAt_stringXiMassCoordinate
#print axioms DerridaRetaux.hasDerivAt_stringXiMassCoordinate
#check DerridaRetaux.hasDerivAt_stringY
#print axioms DerridaRetaux.hasDerivAt_stringY
#check DerridaRetaux.hasIntegralDerivativeOn_Icc_of_local_uniform_and_L1
#print axioms DerridaRetaux.hasIntegralDerivativeOn_Icc_of_local_uniform_and_L1
#check DerridaRetaux.hasIntegralDerivativeOn_of_tendstoUniformly_of_tendstoInL1On
#print axioms DerridaRetaux.hasIntegralDerivativeOn_of_tendstoUniformly_of_tendstoInL1On
#check DerridaRetaux.hasSum_cubicCarrier_natPred_convPow
#print axioms DerridaRetaux.hasSum_cubicCarrier_natPred_convPow
#check DerridaRetaux.initialArrivalU24_tendsto_zero
#print axioms DerridaRetaux.initialArrivalU24_tendsto_zero
#check DerridaRetaux.initialArrival_tail_limits
#print axioms DerridaRetaux.initialArrival_tail_limits
#check DerridaRetaux.integral_cubicTail_le_of_finiteMeasure_tendsto_eventually
#print axioms DerridaRetaux.integral_cubicTail_le_of_finiteMeasure_tendsto_eventually
#check DerridaRetaux.integral_cubicTail_scaledLatticeMeasure_eq_all
#print axioms DerridaRetaux.integral_cubicTail_scaledLatticeMeasure_eq_all
#check DerridaRetaux.integratedExpThirdRemainder_le_cutoff
#print axioms DerridaRetaux.integratedExpThirdRemainder_le_cutoff
#check DerridaRetaux.integratedLaplaceSecondGap_eq
#print axioms DerridaRetaux.integratedLaplaceSecondGap_eq
#check DerridaRetaux.integratedLaplaceSecondGap_nonneg_and_le
#print axioms DerridaRetaux.integratedLaplaceSecondGap_nonneg_and_le
#check DerridaRetaux.integratedLaplaceSecondGap_pos
#print axioms DerridaRetaux.integratedLaplaceSecondGap_pos
#check DerridaRetaux.inversePower_succ_hasSum
#print axioms DerridaRetaux.inversePower_succ_hasSum
#check DerridaRetaux.kotaniCharacteristicFact_imp_cumulative_eq
#print axioms DerridaRetaux.kotaniCharacteristicFact_imp_cumulative_eq
#check DerridaRetaux.latticeLeftRiemannSum_tendsto_intervalIntegral
#print axioms DerridaRetaux.latticeLeftRiemannSum_tendsto_intervalIntegral
#check DerridaRetaux.lawStep
#print axioms DerridaRetaux.lawStep
#check DerridaRetaux.limit_cubicTail_le_of_scaledLatticeMeasuresAlong_tendsto_eventually
#print axioms DerridaRetaux.limit_cubicTail_le_of_scaledLatticeMeasuresAlong_tendsto_eventually
#check DerridaRetaux.locallyUniformLatticeDensity_of_orbitScaledGrid_exhaustionLimits
#print axioms DerridaRetaux.locallyUniformLatticeDensity_of_orbitScaledGrid_exhaustionLimits
#check DerridaRetaux.log_modulus_inverse
#print axioms DerridaRetaux.log_modulus_inverse
#check DerridaRetaux.modelEntranceString
#print axioms DerridaRetaux.modelEntranceString
#check DerridaRetaux.modelEntranceString_correctRightEnd
#print axioms DerridaRetaux.modelEntranceString_correctRightEnd
#check DerridaRetaux.modelEntranceString_hasRightEnd_zero
#print axioms DerridaRetaux.modelEntranceString_hasRightEnd_zero
#check DerridaRetaux.modelEntranceString_hasSecondEntranceMoment
#print axioms DerridaRetaux.modelEntranceString_hasSecondEntranceMoment
#check DerridaRetaux.modelEntranceString_hasSingularCharacteristic
#print axioms DerridaRetaux.modelEntranceString_hasSingularCharacteristic
#check DerridaRetaux.modelEntranceString_hasSingularCharacteristic_of_neg
#print axioms DerridaRetaux.modelEntranceString_hasSingularCharacteristic_of_neg
#check DerridaRetaux.modelEntranceString_isEntranceType
#print axioms DerridaRetaux.modelEntranceString_isEntranceType
#check DerridaRetaux.modelStringDensity
#print axioms DerridaRetaux.modelStringDensity
#check DerridaRetaux.modelStringEndpointSolutionDeriv_neg
#print axioms DerridaRetaux.modelStringEndpointSolutionDeriv_neg
#check DerridaRetaux.modelStringEndpointSolution_ode
#print axioms DerridaRetaux.modelStringEndpointSolution_ode
#check DerridaRetaux.modelStringEndpointSolution_pos
#print axioms DerridaRetaux.modelStringEndpointSolution_pos
#check DerridaRetaux.modelStringEntranceSolution_isVolterra
#print axioms DerridaRetaux.modelStringEntranceSolution_isVolterra
#check DerridaRetaux.modelStringMass
#print axioms DerridaRetaux.modelStringMass
#check DerridaRetaux.model_stringCumulative_of_neg
#print axioms DerridaRetaux.model_stringCumulative_of_neg
#check DerridaRetaux.model_stringCumulative_of_nonneg
#print axioms DerridaRetaux.model_stringCumulative_of_nonneg
#check DerridaRetaux.monotoneOn_entranceSolutionFromEndpoint
#print axioms DerridaRetaux.monotoneOn_entranceSolutionFromEndpoint
#check DerridaRetaux.natFloor_window_div_cofinal_tendsto
#print axioms DerridaRetaux.natFloor_window_div_cofinal_tendsto
#check DerridaRetaux.nat_mul_inversePower_succ_hasSum
#print axioms DerridaRetaux.nat_mul_inversePower_succ_hasSum
#check DerridaRetaux.nat_mul_reciprocal_barrier_tendsto
#print axioms DerridaRetaux.nat_mul_reciprocal_barrier_tendsto
#check DerridaRetaux.negative_of_nonnegative_strict_growth
#print axioms DerridaRetaux.negative_of_nonnegative_strict_growth
#check DerridaRetaux.no_eventual_subquadratic_poweredPrefixProduct_bound
#print axioms DerridaRetaux.no_eventual_subquadratic_poweredPrefixProduct_bound
#check DerridaRetaux.normalizedCubicMoment_drStep_cross
#print axioms DerridaRetaux.normalizedCubicMoment_drStep_cross
#check DerridaRetaux.normalizedCubicMoment_eqJ
#print axioms DerridaRetaux.normalizedCubicMoment_eqJ
#check DerridaRetaux.normalizedCubicMoment_pos_of_profileInitialData
#print axioms DerridaRetaux.normalizedCubicMoment_pos_of_profileInitialData
#check DerridaRetaux.normalizedCubicMoment_profile_orbit_pos
#print axioms DerridaRetaux.normalizedCubicMoment_profile_orbit_pos
#check DerridaRetaux.normalizedTilt
#print axioms DerridaRetaux.normalizedTilt
#check DerridaRetaux.normalizedTiltGeneratingFunction_orbit_succ
#print axioms DerridaRetaux.normalizedTiltGeneratingFunction_orbit_succ
#check DerridaRetaux.normalizedTilt_hasSum
#print axioms DerridaRetaux.normalizedTilt_hasSum
#check DerridaRetaux.normalizedTilt_lowMoments_orbit
#print axioms DerridaRetaux.normalizedTilt_lowMoments_orbit
#check DerridaRetaux.normalizedTilt_mean_hasSum
#print axioms DerridaRetaux.normalizedTilt_mean_hasSum
#check DerridaRetaux.one_add_pow_sub_lower
#print axioms DerridaRetaux.one_add_pow_sub_lower
#check DerridaRetaux.one_le_entranceSolutionFromEndpoint
#print axioms DerridaRetaux.one_le_entranceSolutionFromEndpoint
#check DerridaRetaux.orbit
#print axioms DerridaRetaux.orbit
#check DerridaRetaux.orbitExcess_bound_all
#print axioms DerridaRetaux.orbitExcess_bound_all
#check DerridaRetaux.orbitPositiveTiltMass_bound_all
#print axioms DerridaRetaux.orbitPositiveTiltMass_bound_all
#check DerridaRetaux.orbitPositiveTiltMass_tendsto_zero
#print axioms DerridaRetaux.orbitPositiveTiltMass_tendsto_zero
#check DerridaRetaux.orbitPositiveTilt_eq_product_shift_arrival
#print axioms DerridaRetaux.orbitPositiveTilt_eq_product_shift_arrival
#check DerridaRetaux.orbitScaledGrid
#print axioms DerridaRetaux.orbitScaledGrid
#check DerridaRetaux.orbitScaledGridStepError_tendsto_zero
#print axioms DerridaRetaux.orbitScaledGridStepError_tendsto_zero
#check DerridaRetaux.orbitScaledGrid_adjacent_le_of_gradient
#print axioms DerridaRetaux.orbitScaledGrid_adjacent_le_of_gradient
#check DerridaRetaux.orbitTransportDefect_le_of_positiveTiltMass_bound
#print axioms DerridaRetaux.orbitTransportDefect_le_of_positiveTiltMass_bound
#check DerridaRetaux.orbitTransportDefect_summable
#print axioms DerridaRetaux.orbitTransportDefect_summable
#check DerridaRetaux.orbitZeroTilt_inverse_uniform
#print axioms DerridaRetaux.orbitZeroTilt_inverse_uniform
#check DerridaRetaux.orbitZeroTilt_succ_eq_transportCoeff_mul
#print axioms DerridaRetaux.orbitZeroTilt_succ_eq_transportCoeff_mul
#check DerridaRetaux.orbit_critical
#print axioms DerridaRetaux.orbit_critical
#check DerridaRetaux.orbit_criticalProduct_sub_two_log_isLittleO
#print axioms DerridaRetaux.orbit_criticalProduct_sub_two_log_isLittleO
#check DerridaRetaux.orbit_densityD_natFloor_tendsto_half_of_H1a
#print axioms DerridaRetaux.orbit_densityD_natFloor_tendsto_half_of_H1a
#check DerridaRetaux.orbit_densityD_uniform_after_natFloor_of_H1a
#print axioms DerridaRetaux.orbit_densityD_uniform_after_natFloor_of_H1a
#check DerridaRetaux.orbit_densityD_variation_of_zeroTilt_variation
#print axioms DerridaRetaux.orbit_densityD_variation_of_zeroTilt_variation
#check DerridaRetaux.orbit_densityTotalMass_tendsto_two_of_compact_profile
#print axioms DerridaRetaux.orbit_densityTotalMass_tendsto_two_of_compact_profile
#check DerridaRetaux.orbit_eq_coefficientOrbit
#print axioms DerridaRetaux.orbit_eq_coefficientOrbit
#check DerridaRetaux.orbit_fixedAtom_geometric_bound_of_H1_and_pointwise
#print axioms DerridaRetaux.orbit_fixedAtom_geometric_bound_of_H1_and_pointwise
#check DerridaRetaux.orbit_positiveTiltMass_tendsto_of_compact_profile
#print axioms DerridaRetaux.orbit_positiveTiltMass_tendsto_of_compact_profile
#check DerridaRetaux.orbit_rho_scaled_conv_uniform_on_compact_away_zero
#print axioms DerridaRetaux.orbit_rho_scaled_conv_uniform_on_compact_away_zero
#check DerridaRetaux.orbit_tiltSummable_three
#print axioms DerridaRetaux.orbit_tiltSummable_three
#check DerridaRetaux.orbit_zeroTilt_pos
#print axioms DerridaRetaux.orbit_zeroTilt_pos
#check DerridaRetaux.orbit_zeroTilt_succ_variation_of_bounds
#print axioms DerridaRetaux.orbit_zeroTilt_succ_variation_of_bounds
#check DerridaRetaux.partition_log_sum_div_log_tendsto
#print axioms DerridaRetaux.partition_log_sum_div_log_tendsto
#check DerridaRetaux.partition_tendsto_one_of_survival
#print axioms DerridaRetaux.partition_tendsto_one_of_survival
#check DerridaRetaux.physicalTimeCoordinate_eq_neg_div
#print axioms DerridaRetaux.physicalTimeCoordinate_eq_neg_div
#check DerridaRetaux.physicalTimeLaplaceTransform_eq
#print axioms DerridaRetaux.physicalTimeLaplaceTransform_eq
#check DerridaRetaux.physicalTimeScale_eq
#print axioms DerridaRetaux.physicalTimeScale_eq
#check DerridaRetaux.physicalTimeZerothMoment_eq
#print axioms DerridaRetaux.physicalTimeZerothMoment_eq
#check DerridaRetaux.positiveHalfLineMoment_A3_lower
#print axioms DerridaRetaux.positiveHalfLineMoment_A3_lower
#check DerridaRetaux.positiveHalfLineMoment_one_sq_le_zero_mul_two
#print axioms DerridaRetaux.positiveHalfLineMoment_one_sq_le_zero_mul_two
#check DerridaRetaux.positiveHalfLineMoment_two_sq_le_one_mul_three
#print axioms DerridaRetaux.positiveHalfLineMoment_two_sq_le_one_mul_three
#check DerridaRetaux.positiveHalfLineMoment_zero_and_three_pos
#print axioms DerridaRetaux.positiveHalfLineMoment_zero_and_three_pos
#check DerridaRetaux.positiveTiltMass_eq_excess_add_survival_div
#print axioms DerridaRetaux.positiveTiltMass_eq_excess_add_survival_div
#check DerridaRetaux.positiveTiltMass_le_survival_cutoff
#print axioms DerridaRetaux.positiveTiltMass_le_survival_cutoff
#check DerridaRetaux.positiveTiltMass_orbit_eq
#print axioms DerridaRetaux.positiveTiltMass_orbit_eq
#check DerridaRetaux.positiveTiltMass_tendsto_zero_of_survival
#print axioms DerridaRetaux.positiveTiltMass_tendsto_zero_of_survival
#check DerridaRetaux.positiveTiltedDensity
#print axioms DerridaRetaux.positiveTiltedDensity
#check DerridaRetaux.positiveTiltedDensity_eq_transportRatio_add_quadratic_add_higher
#print axioms DerridaRetaux.positiveTiltedDensity_eq_transportRatio_add_quadratic_add_higher
#check DerridaRetaux.positiveTiltedDensity_firstShifted_tsum
#print axioms DerridaRetaux.positiveTiltedDensity_firstShifted_tsum
#check DerridaRetaux.positiveTiltedDensity_orbit_add_le_shift_add_majorant
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_add_le_shift_add_majorant
#check DerridaRetaux.positiveTiltedDensity_orbit_apply_eq_discreteMildDuhamel
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_apply_eq_discreteMildDuhamel
#check DerridaRetaux.positiveTiltedDensity_orbit_succ
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_succ
#check DerridaRetaux.positiveTiltedDensity_orbit_succ_fullRhoSource
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_succ_fullRhoSource
#check DerridaRetaux.positiveTiltedDensity_orbit_succ_short
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_succ_short
#check DerridaRetaux.positiveTiltedDensity_pointwise_of_H1
#print axioms DerridaRetaux.positiveTiltedDensity_pointwise_of_H1
#check DerridaRetaux.positiveTiltedDensity_pointwise_of_arrival_far
#print axioms DerridaRetaux.positiveTiltedDensity_pointwise_of_arrival_far
#check DerridaRetaux.positiveTiltedDensity_scaledPointwise_of_far_and_weightedL1
#print axioms DerridaRetaux.positiveTiltedDensity_scaledPointwise_of_far_and_weightedL1
#check DerridaRetaux.positiveTiltedDensity_spatialSmoothing_of_H1
#print axioms DerridaRetaux.positiveTiltedDensity_spatialSmoothing_of_H1
#check DerridaRetaux.positiveTiltedDensity_temporalModulus_of_H1_and_spatial
#print axioms DerridaRetaux.positiveTiltedDensity_temporalModulus_of_H1_and_spatial
#check DerridaRetaux.positiveTiltedDensity_weightedMass_orbit
#print axioms DerridaRetaux.positiveTiltedDensity_weightedMass_orbit
#check DerridaRetaux.probabilityFirstMoment_tendsto_of_atom_limits_and_bound
#print axioms DerridaRetaux.probabilityFirstMoment_tendsto_of_atom_limits_and_bound
#check DerridaRetaux.probabilityMassTail_tendsto_zero
#print axioms DerridaRetaux.probabilityMassTail_tendsto_zero
#check DerridaRetaux.profileDensityMomentTail_uniform_integrability_of_spineTail
#print axioms DerridaRetaux.profileDensityMomentTail_uniform_integrability_of_spineTail
#check DerridaRetaux.profileDensityMoment_tendsto_of_compact_heads_and_spineTail_along
#print axioms DerridaRetaux.profileDensityMoment_tendsto_of_compact_heads_and_spineTail_along
#check DerridaRetaux.profileDensityThirdTail_uniform_integrability_of_spineTail
#print axioms DerridaRetaux.profileDensityThirdTail_uniform_integrability_of_spineTail
#check DerridaRetaux.profileScale
#print axioms DerridaRetaux.profileScale
#check DerridaRetaux.profileScale_pos
#print axioms DerridaRetaux.profileScale_pos
#check DerridaRetaux.profileThirdTail_quadratic_of_concreteSpine
#print axioms DerridaRetaux.profileThirdTail_quadratic_of_concreteSpine
#check DerridaRetaux.profileThirdTail_quadratic_of_spineTail
#print axioms DerridaRetaux.profileThirdTail_quadratic_of_spineTail
#check DerridaRetaux.profileThirdTail_uniform_integrability_of_concreteSpine
#print axioms DerridaRetaux.profileThirdTail_uniform_integrability_of_concreteSpine
#check DerridaRetaux.profileThirdTail_uniform_integrability_of_spineTail
#print axioms DerridaRetaux.profileThirdTail_uniform_integrability_of_spineTail
#check DerridaRetaux.quadraticDensityAt_lipschitz_on_unit
#print axioms DerridaRetaux.quadraticDensityAt_lipschitz_on_unit
#check DerridaRetaux.scaledDensityTailL1_tendsto_zero_of_weighted
#print axioms DerridaRetaux.scaledDensityTailL1_tendsto_zero_of_weighted
#check DerridaRetaux.scaledDiscreteMoment_tendsto_of_heads_and_uniform_tails_along
#print axioms DerridaRetaux.scaledDiscreteMoment_tendsto_of_heads_and_uniform_tails_along
#check DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_finiteDensityMeasure_of_locallyUniform
#print axioms DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_finiteDensityMeasure_of_locallyUniform
#check DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_of_exhaustionLimits
#print axioms DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_of_exhaustionLimits
#check DerridaRetaux.scaled_conv_eq_lattice_product_sum
#print axioms DerridaRetaux.scaled_conv_eq_lattice_product_sum
#check DerridaRetaux.scaled_conv_gridIndex_tendsto_of_locallyUniform_of_nonneg
#print axioms DerridaRetaux.scaled_conv_gridIndex_tendsto_of_locallyUniform_of_nonneg
#check DerridaRetaux.scaled_conv_tendsto_moving_of_locallyUniform
#print axioms DerridaRetaux.scaled_conv_tendsto_moving_of_locallyUniform
#check DerridaRetaux.scaled_conv_uniform_on_compact_away_zero_of_locallyUniform
#print axioms DerridaRetaux.scaled_conv_uniform_on_compact_away_zero_of_locallyUniform
#check DerridaRetaux.scaled_shiftRightPow_conv_gridIndex_tendsto_of_nonneg
#print axioms DerridaRetaux.scaled_shiftRightPow_conv_gridIndex_tendsto_of_nonneg
#check DerridaRetaux.scaled_smoothing_rate_le_log
#print axioms DerridaRetaux.scaled_smoothing_rate_le_log
#check DerridaRetaux.seq_recurrence_apply_eq_transport_add_forcing
#print axioms DerridaRetaux.seq_recurrence_apply_eq_transport_add_forcing
#check DerridaRetaux.seq_recurrence_eq_truncatedInitial_add_forcing
#print axioms DerridaRetaux.seq_recurrence_eq_truncatedInitial_add_forcing
#check DerridaRetaux.sharpOriginalLaw
#print axioms DerridaRetaux.sharpOriginalLaw
#check DerridaRetaux.sharpOriginalLaw_critical
#print axioms DerridaRetaux.sharpOriginalLaw_critical
#check DerridaRetaux.sharpOriginalLaw_not_isDirac
#print axioms DerridaRetaux.sharpOriginalLaw_not_isDirac
#check DerridaRetaux.sharpOriginalLaw_not_tiltSummable_three
#print axioms DerridaRetaux.sharpOriginalLaw_not_tiltSummable_three
#check DerridaRetaux.sharpOriginalLaw_realTiltSummable_iff
#print axioms DerridaRetaux.sharpOriginalLaw_realTiltSummable_iff
#check DerridaRetaux.sharpOriginalLaw_tail
#print axioms DerridaRetaux.sharpOriginalLaw_tail
#check DerridaRetaux.sharpPowerExponent
#print axioms DerridaRetaux.sharpPowerExponent
#check DerridaRetaux.sharpTailConstant_pos
#print axioms DerridaRetaux.sharpTailConstant_pos
#check DerridaRetaux.sharpTiltedSeq_first_hasSum
#print axioms DerridaRetaux.sharpTiltedSeq_first_hasSum
#check DerridaRetaux.sharpTiltedSeq_hasSum_one
#print axioms DerridaRetaux.sharpTiltedSeq_hasSum_one
#check DerridaRetaux.sharpTiltedSeq_nonneg
#print axioms DerridaRetaux.sharpTiltedSeq_nonneg
#check DerridaRetaux.sharpnessPowerLaw_not_partition_excess_limit
#print axioms DerridaRetaux.sharpnessPowerLaw_not_partition_excess_limit
#check DerridaRetaux.shiftByInt
#print axioms DerridaRetaux.shiftByInt
#check DerridaRetaux.shiftLeft
#print axioms DerridaRetaux.shiftLeft
#check DerridaRetaux.shiftRight
#print axioms DerridaRetaux.shiftRight
#check DerridaRetaux.shiftedCubicMoment_convPow_summable_and_le
#print axioms DerridaRetaux.shiftedCubicMoment_convPow_summable_and_le
#check DerridaRetaux.shiftedPowerTailMoment_summable_iff
#print axioms DerridaRetaux.shiftedPowerTailMoment_summable_iff
#check DerridaRetaux.shortDensityStep
#print axioms DerridaRetaux.shortDensityStep
#check DerridaRetaux.smoothingRemainder
#print axioms DerridaRetaux.smoothingRemainder
#check DerridaRetaux.smoothingRemainders_orbit_of_H1_and_pointwise
#print axioms DerridaRetaux.smoothingRemainders_orbit_of_H1_and_pointwise
#check DerridaRetaux.smoothing_coefficients_orbit_bounds
#print axioms DerridaRetaux.smoothing_coefficients_orbit_bounds
#check DerridaRetaux.sourceChoiceOrder_eq_tag_q
#print axioms DerridaRetaux.sourceChoiceOrder_eq_tag_q
#check DerridaRetaux.sourceDifference_triangle_le_of_tailControlled
#print axioms DerridaRetaux.sourceDifference_triangle_le_of_tailControlled
#check DerridaRetaux.sourceFactorValue_eq_coreNormalForm
#print axioms DerridaRetaux.sourceFactorValue_eq_coreNormalForm
#check DerridaRetaux.sourceFunctionExpandedTerm_eq_tagNormalForm
#print axioms DerridaRetaux.sourceFunctionExpandedTerm_eq_tagNormalForm
#check DerridaRetaux.sourceModelEntranceString_hasSingularCharacteristic
#print axioms DerridaRetaux.sourceModelEntranceString_hasSingularCharacteristic
#check DerridaRetaux.spineInfinitePathMeasure_marginal
#print axioms DerridaRetaux.spineInfinitePathMeasure_marginal
#check DerridaRetaux.spineMarginalPMF_bind_spineKernel
#print axioms DerridaRetaux.spineMarginalPMF_bind_spineKernel
#check DerridaRetaux.spineMarginalPMF_bind_spineKernel_all
#print axioms DerridaRetaux.spineMarginalPMF_bind_spineKernel_all
#check DerridaRetaux.spinePathPMF
#print axioms DerridaRetaux.spinePathPMF
#check DerridaRetaux.spinePathPMF_initial_marginal
#print axioms DerridaRetaux.spinePathPMF_initial_marginal
#check DerridaRetaux.spinePathPMF_terminal_marginal
#print axioms DerridaRetaux.spinePathPMF_terminal_marginal
#check DerridaRetaux.spinePath_positiveVariation_hasSum
#print axioms DerridaRetaux.spinePath_positiveVariation_hasSum
#check DerridaRetaux.spineSharpTail_le_initial_add
#print axioms DerridaRetaux.spineSharpTail_le_initial_add
#check DerridaRetaux.squareWeightSum_le
#print axioms DerridaRetaux.squareWeightSum_le
#check DerridaRetaux.squareWeightSummationByParts_source
#print axioms DerridaRetaux.squareWeightSummationByParts_source
#check DerridaRetaux.strictAntiOn_constructedEndpointSolution
#print axioms DerridaRetaux.strictAntiOn_constructedEndpointSolution
#check DerridaRetaux.strictAntiOn_modelStringEndpointSolution
#print axioms DerridaRetaux.strictAntiOn_modelStringEndpointSolution
#check DerridaRetaux.strictMonoOn_stringXi
#print axioms DerridaRetaux.strictMonoOn_stringXi
#check DerridaRetaux.stringA2Y
#print axioms DerridaRetaux.stringA2Y
#check DerridaRetaux.stringA2Y_two_sided
#print axioms DerridaRetaux.stringA2Y_two_sided
#check DerridaRetaux.stringDensityCoefficient_vs_coordinate
#print axioms DerridaRetaux.stringDensityCoefficient_vs_coordinate
#check DerridaRetaux.stringMassPrimitive
#print axioms DerridaRetaux.stringMassPrimitive
#check DerridaRetaux.stringXi
#print axioms DerridaRetaux.stringXi
#check DerridaRetaux.stringXiMassCoordinate_comp_eq
#print axioms DerridaRetaux.stringXiMassCoordinate_comp_eq
#check DerridaRetaux.stringXiMassCoordinate_two_sided
#print axioms DerridaRetaux.stringXiMassCoordinate_two_sided
#check DerridaRetaux.stringXi_bijOn
#print axioms DerridaRetaux.stringXi_bijOn
#check DerridaRetaux.stringXi_eq_neg_integral_Ioi
#print axioms DerridaRetaux.stringXi_eq_neg_integral_Ioi
#check DerridaRetaux.stringY
#print axioms DerridaRetaux.stringY
#check DerridaRetaux.stringY_eq_stringXi_sq_div_of_cumulative_eq_model
#print axioms DerridaRetaux.stringY_eq_stringXi_sq_div_of_cumulative_eq_model
#check DerridaRetaux.stringY_two_sided
#print axioms DerridaRetaux.stringY_two_sided
#check DerridaRetaux.sum_range_sum_range_triangle
#print axioms DerridaRetaux.sum_range_sum_range_triangle
#check DerridaRetaux.sum_sourceFactorCoreExcess_eq_tag_e
#print axioms DerridaRetaux.sum_sourceFactorCoreExcess_eq_tag_e
#check DerridaRetaux.summable_partition_excess_sq
#print axioms DerridaRetaux.summable_partition_excess_sq
#check DerridaRetaux.survival
#print axioms DerridaRetaux.survival
#check DerridaRetaux.survivalBarrierPolynomial_factor
#print axioms DerridaRetaux.survivalBarrierPolynomial_factor
#check DerridaRetaux.survivalReadout
#print axioms DerridaRetaux.survivalReadout
#check DerridaRetaux.survival_eq_partition_mul_readout
#print axioms DerridaRetaux.survival_eq_partition_mul_readout
#check DerridaRetaux.survival_le_excess_div_of_critical
#print axioms DerridaRetaux.survival_le_excess_div_of_critical
#check DerridaRetaux.survival_sub_boundary_le
#print axioms DerridaRetaux.survival_sub_boundary_le
#check DerridaRetaux.taggedSourceTerm_tailControlled_of_H1
#print axioms DerridaRetaux.taggedSourceTerm_tailControlled_of_H1
#check DerridaRetaux.taggedSourceTerm_tailControlled_of_q_eq_zero
#print axioms DerridaRetaux.taggedSourceTerm_tailControlled_of_q_eq_zero
#check DerridaRetaux.taggedSourceTerm_tailControlled_of_q_pos
#print axioms DerridaRetaux.taggedSourceTerm_tailControlled_of_q_pos
#check DerridaRetaux.taggedSourceTerm_tailControlled_uniform
#print axioms DerridaRetaux.taggedSourceTerm_tailControlled_uniform
#check DerridaRetaux.tendsto_constructedEndpointSolution_nhdsLT_zero
#print axioms DerridaRetaux.tendsto_constructedEndpointSolution_nhdsLT_zero
#check DerridaRetaux.tendsto_constructed_stringCumulative_nhds_top
#print axioms DerridaRetaux.tendsto_constructed_stringCumulative_nhds_top
#check DerridaRetaux.tendsto_entranceSolutionFromEndpoint_atBot_one
#print axioms DerridaRetaux.tendsto_entranceSolutionFromEndpoint_atBot_one
#check DerridaRetaux.tendsto_modelStringEndpointSolutionDeriv_atBot
#print axioms DerridaRetaux.tendsto_modelStringEndpointSolutionDeriv_atBot
#check DerridaRetaux.tendsto_modelStringEndpointSolution_add_id_atBot
#print axioms DerridaRetaux.tendsto_modelStringEndpointSolution_add_id_atBot
#check DerridaRetaux.tendsto_modelStringEndpointSolution_nhdsLT_zero
#print axioms DerridaRetaux.tendsto_modelStringEndpointSolution_nhdsLT_zero
#check DerridaRetaux.tendsto_model_stringCumulative_nhdsLT_zero_top
#print axioms DerridaRetaux.tendsto_model_stringCumulative_nhdsLT_zero_top
#check DerridaRetaux.tendsto_transportProduct_of_defect_summable
#print axioms DerridaRetaux.tendsto_transportProduct_of_defect_summable
#check DerridaRetaux.terminalTransportWeight_orbit_natFloor_window_uniform_of_H1a
#print axioms DerridaRetaux.terminalTransportWeight_orbit_natFloor_window_uniform_of_H1a
#check DerridaRetaux.tiltSummable_three_drStep
#print axioms DerridaRetaux.tiltSummable_three_drStep
#check DerridaRetaux.tiltedPartition
#print axioms DerridaRetaux.tiltedPartition
#check DerridaRetaux.tiltedPartition_orbit_succ_eq
#print axioms DerridaRetaux.tiltedPartition_orbit_succ_eq
#check DerridaRetaux.transportBetween_eq_transportProduct_div
#print axioms DerridaRetaux.transportBetween_eq_transportProduct_div
#check DerridaRetaux.transportBetween_orbit_tendsto_one_along_of_H1a
#print axioms DerridaRetaux.transportBetween_orbit_tendsto_one_along_of_H1a
#check DerridaRetaux.transportBetween_orbit_uniform_on_natFloor_window_of_H1a
#print axioms DerridaRetaux.transportBetween_orbit_uniform_on_natFloor_window_of_H1a
#check DerridaRetaux.transportCoeff
#print axioms DerridaRetaux.transportCoeff
#check DerridaRetaux.transportCoeff_inverse_uniform
#print axioms DerridaRetaux.transportCoeff_inverse_uniform
#check DerridaRetaux.transportCoeff_le_one
#print axioms DerridaRetaux.transportCoeff_le_one
#check DerridaRetaux.transportCoeff_pos
#print axioms DerridaRetaux.transportCoeff_pos
#check DerridaRetaux.transportDefect_le_quadratic
#print axioms DerridaRetaux.transportDefect_le_quadratic
#check DerridaRetaux.transportDefect_nonneg
#print axioms DerridaRetaux.transportDefect_nonneg
#check DerridaRetaux.transportDefect_one
#print axioms DerridaRetaux.transportDefect_one
#check DerridaRetaux.transportProduct
#print axioms DerridaRetaux.transportProduct
#check DerridaRetaux.transportProductLimit_pos_of_defect_summable
#print axioms DerridaRetaux.transportProductLimit_pos_of_defect_summable
#check DerridaRetaux.transportProduct_inverse_uniform
#print axioms DerridaRetaux.transportProduct_inverse_uniform
#check DerridaRetaux.transportProduct_mul_zeroTilt_le_orbitZeroTilt
#print axioms DerridaRetaux.transportProduct_mul_zeroTilt_le_orbitZeroTilt
#check DerridaRetaux.transportProduct_tendsto_pos
#print axioms DerridaRetaux.transportProduct_tendsto_pos
#check DerridaRetaux.truncatedSmoothingSplit_of_H1
#print axioms DerridaRetaux.truncatedSmoothingSplit_of_H1
#check DerridaRetaux.weakEquationRhs
#print axioms DerridaRetaux.weakEquationRhs
#check DerridaRetaux.weakQuadraticPairing_eq_integral_positiveSelfConvolution
#print axioms DerridaRetaux.weakQuadraticPairing_eq_integral_positiveSelfConvolution
#check DerridaRetaux.weightedL1Three
#print axioms DerridaRetaux.weightedL1Three
#check DerridaRetaux.weightedL1Three_convPow_le_pow
#print axioms DerridaRetaux.weightedL1Three_convPow_le_pow
#check DerridaRetaux.weightedL1Three_conv_le
#print axioms DerridaRetaux.weightedL1Three_conv_le
#check DerridaRetaux.weightedL1Three_positiveTiltedDensity_le
#print axioms DerridaRetaux.weightedL1Three_positiveTiltedDensity_le
#check DerridaRetaux.weightedL1Three_shiftLeft_le
#print axioms DerridaRetaux.weightedL1Three_shiftLeft_le
#check DerridaRetaux.weightedSupThree_convPow_succ_le
#print axioms DerridaRetaux.weightedSupThree_convPow_succ_le
#check DerridaRetaux.weightedSupThree_conv_le
#print axioms DerridaRetaux.weightedSupThree_conv_le
#check DerridaRetaux.weightedSupThree_shiftByInt_nat
#print axioms DerridaRetaux.weightedSupThree_shiftByInt_nat
#check DerridaRetaux.weightedSupThree_shiftLeft
#print axioms DerridaRetaux.weightedSupThree_shiftLeft
#check DerridaRetaux.weightedSupThree_shiftLeft_iterate_gain
#print axioms DerridaRetaux.weightedSupThree_shiftLeft_iterate_gain
#check DerridaRetaux.weightedSupThree_twoParameter_log_of_split
#print axioms DerridaRetaux.weightedSupThree_twoParameter_log_of_split
#check DerridaRetaux.weightedSupThree_twoParameter_of_split
#print axioms DerridaRetaux.weightedSupThree_twoParameter_of_split
#check DerridaRetaux.yaglomDensity_eq_of_laplace
#print axioms DerridaRetaux.yaglomDensity_eq_of_laplace
#check DerridaRetaux.yaglomDensity_hasWeakEquationOn
#print axioms DerridaRetaux.yaglomDensity_hasWeakEquationOn
#check DerridaRetaux.yaglomDensity_transport_integration_by_parts
#print axioms DerridaRetaux.yaglomDensity_transport_integration_by_parts
#check DerridaRetaux.zeroExtend
#print axioms DerridaRetaux.zeroExtend
#check DerridaRetaux.zeroTilt_pos_of_admissible
#print axioms DerridaRetaux.zeroTilt_pos_of_admissible
