import DerridaRetaux.Analysis.EventuallyLocalUniform
import DerridaRetaux.Analysis.UniformLatticeCriterion
import DerridaRetaux.Analysis.MildEquation

#print axioms DerridaRetaux.locallyUniformLatticeDensity_of_eventually
#print axioms DerridaRetaux.locallyUniformLatticeDensity_of_eventually_epsilon
#print axioms DerridaRetaux.locallyUniformSpacetimeLatticeDensity_orbit_of_gluedExhaustion
#print axioms DerridaRetaux.scaled_conv_shifted_floor_window_uniform
#print axioms DerridaRetaux.densityQuadraticWeight_natFloor_window_uniform_of_H1a
#print axioms DerridaRetaux.quadraticDuhamelGridSum_tendsto_of_H1a
#print axioms DerridaRetaux.scaled_densityQuadraticSegment_tendsto_of_H1a
#print axioms DerridaRetaux.scaled_densityInitialSegment_tendsto_of_H1a
#print axioms DerridaRetaux.scaled_densityHigherSegment_floor_tendsto_zero
#print axioms DerridaRetaux.scaled_terminalDensity_tendsto
#print axioms DerridaRetaux.continuousOn_shiftedConvolutionTimeIntegral
#print axioms DerridaRetaux.gluedExhaustionLimit_mild_pos_of_H1a
#print axioms DerridaRetaux.gluedExhaustionLimit_mild_zero_of_H1a
#print axioms DerridaRetaux.gluedExhaustionLimit_mild_of_H1a
