import DerridaRetaux.Analysis.ConvolutionNorms
import DerridaRetaux.Analysis.ConditionalTV
import DerridaRetaux.Analysis.AtomDomination
import DerridaRetaux.Analysis.BoundaryPointwise
import DerridaRetaux.Analysis.DecrementLimit
import DerridaRetaux.Analysis.DensityMassFixedCutoff
import DerridaRetaux.Analysis.DensityMassFromCompact
import DerridaRetaux.Analysis.DensityMassLimit
import DerridaRetaux.Analysis.DiscreteMildDuhamel
import DerridaRetaux.Analysis.ExpRemainder
import DerridaRetaux.Analysis.ExcessConsequences
import DerridaRetaux.Analysis.ExponentialGrid
import DerridaRetaux.Analysis.GridInterpolation
import DerridaRetaux.Analysis.GridCompactness
import DerridaRetaux.Analysis.GluedExhaustionLimit
import DerridaRetaux.Analysis.EventuallyLocalUniform
import DerridaRetaux.Analysis.UniformLatticeCriterion
import DerridaRetaux.Analysis.GluedTimeSlice
import DerridaRetaux.Analysis.GluedTimeSliceOrbit
import DerridaRetaux.Analysis.SpacetimeLatticeDensity
import DerridaRetaux.Analysis.GridReadout
import DerridaRetaux.Analysis.HigherSourceVanishing
import DerridaRetaux.Analysis.IntegratedRemainder
import DerridaRetaux.Analysis.LatticeMeasure
import DerridaRetaux.Analysis.LatticeRiemannLimit
import DerridaRetaux.Analysis.LatticeWeakConvergence
import DerridaRetaux.Analysis.LaplaceGap
import DerridaRetaux.Analysis.ImproperFTCNonneg
import DerridaRetaux.Analysis.LimitTail
import DerridaRetaux.Analysis.LocalACClosure
import DerridaRetaux.Analysis.LogRate
import DerridaRetaux.Analysis.MeanConsequences
import DerridaRetaux.Analysis.MildCoefficientLimits
import DerridaRetaux.Analysis.MomentPassage
import DerridaRetaux.Analysis.OrbitConvolutionBounds
import DerridaRetaux.Analysis.PointwiseFromFar
import DerridaRetaux.Analysis.ProfileConsequences
import DerridaRetaux.Analysis.QuadraticConvolutionLimit
import DerridaRetaux.Analysis.ReadoutBounds
import DerridaRetaux.Analysis.ReadoutConsequences
import DerridaRetaux.Analysis.SmoothingAlgebra
import DerridaRetaux.Analysis.SmoothingBounds
import DerridaRetaux.Analysis.SmoothingOrbitBounds
import DerridaRetaux.Analysis.SpatialTelescoping
import DerridaRetaux.Analysis.TransportPolynomial
import DerridaRetaux.Analysis.TruncatedSmoothingBounds
import DerridaRetaux.Analysis.TruncatedTelescope
import DerridaRetaux.Analysis.TimeRiemannLimit
import DerridaRetaux.Analysis.WeightedNorm
import DerridaRetaux.Analysis.UniformParameterizedRiemann
import DerridaRetaux.Analysis.SpacetimeConvolutionRiemann
import DerridaRetaux.Analysis.SpacetimeConvolutionLimit
import DerridaRetaux.Analysis.ConvolutionNearZero
import DerridaRetaux.Analysis.ConvolutionContinuity
import DerridaRetaux.Analysis.ConvolutionContinuityOn
import DerridaRetaux.Analysis.FloorTransportGeometry
import DerridaRetaux.Analysis.FloorTransportBoxGeometry
import DerridaRetaux.Analysis.ConvolutionTriangle
import DerridaRetaux.Analysis.ShiftedSpacetimeConvolution
import DerridaRetaux.Analysis.MildQuadraticCoefficient
import DerridaRetaux.Analysis.UniformProductHalf
import DerridaRetaux.Analysis.ShiftedConvolutionBound
import DerridaRetaux.Analysis.QuadraticDuhamelIntegrand
import DerridaRetaux.Analysis.UniformWindowError
import DerridaRetaux.Analysis.LocalizedTimeRiemann
import DerridaRetaux.Analysis.GluedCompactBox
import DerridaRetaux.Analysis.QuadraticDuhamelRiemann
import DerridaRetaux.Analysis.QuadraticDuhamelScaling
import DerridaRetaux.Analysis.QuadraticSegmentLimit
import DerridaRetaux.Analysis.SpacetimeMovingReadout
import DerridaRetaux.Analysis.InitialSegmentLimit
import DerridaRetaux.Analysis.HigherSegmentFloorLimit
import DerridaRetaux.Analysis.TerminalReadoutLimit
import DerridaRetaux.Analysis.MildEquationLimit
import DerridaRetaux.Analysis.MildIntegralContinuity
import DerridaRetaux.Analysis.MildEquationBoundary
import DerridaRetaux.Analysis.MildEquation
import DerridaRetaux.Analysis.WeakIntegratedIdentity
import DerridaRetaux.Analysis.HalfLineIntegrability
import DerridaRetaux.Analysis.WeightedMomentBound
import DerridaRetaux.Analysis.ContinuumMomentIntegrability
import DerridaRetaux.Analysis.HalfLineMomentTransfer
import DerridaRetaux.Analysis.OrbitMomentBound
import DerridaRetaux.Analysis.MomentConvergenceFromLocal
import DerridaRetaux.Analysis.MomentConvergence
import DerridaRetaux.Analysis.OrbitMomentEnvelope
import DerridaRetaux.Analysis.LatticeWeakFromLocal
import DerridaRetaux.Analysis.GluedLimitProperties
import DerridaRetaux.Main.ContinuumMild
import DerridaRetaux.Main.ContinuumMoments
import DerridaRetaux.Main.ContinuumMomentPassage
import DerridaRetaux.Main.ContinuumMomentBounds
import DerridaRetaux.Main.ContinuumThirdTail
import DerridaRetaux.Arrival.ArrivalRecursion
import DerridaRetaux.Arrival.InitialTail
import DerridaRetaux.Arrival.IntegerShift
import DerridaRetaux.Arrival.SourceDifference
import DerridaRetaux.Arrival.SourceDifferenceBound
import DerridaRetaux.Arrival.SourceNormalForm
import DerridaRetaux.Arrival.VisitOnce
import DerridaRetaux.Audit.ArchitectureCounterexample
import DerridaRetaux.Basic.Convolution
import DerridaRetaux.Basic.CriticalExamples
import DerridaRetaux.Basic.PMFBridge
import DerridaRetaux.Basic.ProbabilityMass
import DerridaRetaux.Basic.RecursionBridge
import DerridaRetaux.Basic.Sequence
import DerridaRetaux.Basic.WeightedConvolution
import DerridaRetaux.ExternalSignatures
import DerridaRetaux.Main.Arrival
import DerridaRetaux.Main.ArrivalBounds
import DerridaRetaux.Main.DiscreteMoment
import DerridaRetaux.Main.Sharpness
import DerridaRetaux.Main.SharpnessCore
import DerridaRetaux.Main.Smoothing
import DerridaRetaux.Main.Spine
import DerridaRetaux.Main.SpineCore
import DerridaRetaux.Model.CoarseRelations
import DerridaRetaux.Model.Criticality
import DerridaRetaux.Model.DensityRecursion
import DerridaRetaux.Model.GeneratingFunction
import DerridaRetaux.Model.MomentPropagation
import DerridaRetaux.Model.NormalizedTilt
import DerridaRetaux.Model.Observables
import DerridaRetaux.Model.Readout
import DerridaRetaux.Model.Recursion
import DerridaRetaux.Model.Tilted
import DerridaRetaux.Model.TiltedProperties
import DerridaRetaux.Model.TiltedRecursion
import DerridaRetaux.Model.TransportCoefficient
import DerridaRetaux.Model.TransportLimit
import DerridaRetaux.Model.ZeroAtom
import DerridaRetaux.Prelim.AtomTail
import DerridaRetaux.Prelim.AtomTailAbel
import DerridaRetaux.Prelim.CoarseMomentBounds
import DerridaRetaux.Prelim.CubicMoment
import DerridaRetaux.Prelim.FarTail
import DerridaRetaux.Prelim.TransportUniform
import DerridaRetaux.Prelim.WeightedMass
import DerridaRetaux.Prelim.WeightedMassOrbit
import DerridaRetaux.Rigidity.EntranceStringBase
import DerridaRetaux.Rigidity.EntranceStringSmoke
import DerridaRetaux.Rigidity.ConstructedSolution
import DerridaRetaux.Rigidity.ConstructedEndpointProperties
import DerridaRetaux.Rigidity.CharacteristicReduction
import DerridaRetaux.Rigidity.ConstructedEntranceExpansion
import DerridaRetaux.Rigidity.ConstructedEndpointGlobal
import DerridaRetaux.Rigidity.ConstructedEndpointAsymptotics
import DerridaRetaux.Rigidity.ModelString
import DerridaRetaux.Rigidity.ModelCharacteristicFinal
import DerridaRetaux.Rigidity.ModelCharacteristicParameter
import DerridaRetaux.Rigidity.PhysicalTime
import DerridaRetaux.Rigidity.StringCoordinates
import DerridaRetaux.Rigidity.StringAdmissibility
import DerridaRetaux.Rigidity.Translation
import DerridaRetaux.Sharpness.PowerTail
import DerridaRetaux.Sharpness.LogCesaro
import DerridaRetaux.Sharpness.ProductContradiction
import DerridaRetaux.Sharpness.StableProduct
import DerridaRetaux.Spine.SizeBiased
import DerridaRetaux.Spine.Allocation
import DerridaRetaux.Spine.Kernel
import DerridaRetaux.Spine.CompanionExpectations
import DerridaRetaux.Spine.Coupling
import DerridaRetaux.Spine.ConcreteTail
import DerridaRetaux.Spine.OutputMarginal
import DerridaRetaux.Spine.IncrementBound
import DerridaRetaux.Spine.FactorialCauchy
import DerridaRetaux.Spine.PathTail
import DerridaRetaux.Spine.ThirdTail

/-!
# Project axiom audit

Representative public results from every currently compilable project module are printed
below.  This file is an executable trust-boundary check: its output should contain only
Lean's standard quotient, choice, and propositional-extensionality axioms.
-/

#print axioms DerridaRetaux.squareWeightSummationByParts_source
#print axioms DerridaRetaux.inverseLinear_isIntegerRegularlyVaryingNegOne
#print axioms DerridaRetaux.profileScale_pos
#print axioms DerridaRetaux.integrableOn_Iic_deriv_of_nonneg'

#print axioms DerridaRetaux.critical_isDirac_eq_binary

#print axioms DerridaRetaux.ProbabilityMass.ofPMF_toPMF
#print axioms DerridaRetaux.ProbabilityMass.toPMF_ofPMF

#print axioms DerridaRetaux.orbit_toPMF_succ

#print axioms DerridaRetaux.continuous_gridBilinearInterp
#print axioms DerridaRetaux.gridBilinearInterp_at_node
#print axioms DerridaRetaux.natSquare_mul_log_gradient_rate_tendsto_zero
#print axioms DerridaRetaux.probabilityFirstMoment_summable_of_tiltSummable
#print axioms DerridaRetaux.orbit_probabilityFirstMoment_tendsto_of_atom_limits
#print axioms DerridaRetaux.orbit_probabilityFirstMoment_tendsto_of_atom_limits_and_bound
#print axioms DerridaRetaux.conditionalFirstMoment_tendsto
#print axioms DerridaRetaux.orbitPartition_tendsto_one_of_H1
#print axioms DerridaRetaux.orbit_fixedAtom_geometric_bound_of_H1_and_pointwise
#print axioms DerridaRetaux.boundaryDensity_tendsto_of_compact_profile_error
#print axioms DerridaRetaux.fixedAtom_tendsto_of_compact_profile_error
#print axioms DerridaRetaux.orbitPartition_tendsto_one_of_scaled_excess
#print axioms DerridaRetaux.survival_tendsto_of_boundary_partition_gradient
#print axioms DerridaRetaux.survival_tendsto_of_compact_profile_excess_gradient
#print axioms DerridaRetaux.survival_tendsto_of_boundary_partition_log_gradient

#print axioms DerridaRetaux.expThirdRemainder_bounds
#print axioms DerridaRetaux.expThirdRemainder_le_smallCutoff
#print axioms DerridaRetaux.densityCoeff_nonneg_and_le_choose
#print axioms DerridaRetaux.densityE_orbit_weightedSup_order_four
#print axioms DerridaRetaux.densityE_orbit_weightedL1_order_three
#print axioms DerridaRetaux.densityR_orbit_weightedSup_order_four
#print axioms DerridaRetaux.smoothingRemainders_orbit_of_H1_and_pointwise

#print axioms DerridaRetaux.densityTotalMass_eq_tiltFactor_mul_positiveTiltMass
#print axioms DerridaRetaux.nat_mul_tendsto_zero_of_natSquare_mul_tendsto
#print axioms DerridaRetaux.orbit_scaledExcess_tendsto_of_densityMass_and_survival
#print axioms DerridaRetaux.natCast_mul_one_sub_exp_neg_two_div_tendsto_two
#print axioms DerridaRetaux.exponentialProfile_gridMass_tendsto_two
#print axioms DerridaRetaux.exponentialProfileGridTail_tendsto_zero
#print axioms DerridaRetaux.scaled_tsum_tendsto_two_of_local_profile_and_weighted_tail
#print axioms DerridaRetaux.orbit_densityTotalMass_tendsto_two_of_local_profile_and_weighted_tail
#print axioms DerridaRetaux.orbit_positiveTiltMass_tendsto_of_local_profile_and_weighted_tail
#print axioms DerridaRetaux.linearProfileCutoff_ratio_tendsto
#print axioms DerridaRetaux.densityProfileL1Error_tendsto_zero_of_fixed_windows
#print axioms DerridaRetaux.orbit_densityTotalMass_tendsto_two_of_fixed_windows
#print axioms DerridaRetaux.densityProfilePrefixL1Error_linearCutoff_tendsto_zero_of_compact
#print axioms DerridaRetaux.orbit_densityTotalMass_tendsto_two_of_compact_profile
#print axioms DerridaRetaux.orbit_positiveTiltMass_tendsto_of_compact_profile

#print axioms DerridaRetaux.inversePower_succ_hasSum
#print axioms DerridaRetaux.survival_sub_boundary_le
#print axioms DerridaRetaux.rho_sub_tiltFactor_mul_survivalReadout_le
#print axioms DerridaRetaux.conditionalPositiveL1Error_profile_scale_le
#print axioms DerridaRetaux.conditionalPositiveL1Error_isBigO_of_profile_scale
#print axioms DerridaRetaux.conditionalPositiveL1Error_eq_two_mul_totalVariation
#print axioms DerridaRetaux.scaledSurvivalReadout_tendsto
#print axioms DerridaRetaux.eventually_inverseSquare_lower_of_scaled_tendsto_pos
#print axioms DerridaRetaux.orbit_conditionalPositiveL1Error_isBigO
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_succ_short
#print axioms DerridaRetaux.densityB_orbit_succ
#print axioms DerridaRetaux.densityE_two
#print axioms DerridaRetaux.densityE_weightedSup_bound
#print axioms DerridaRetaux.densityE_weightedL1_bound
#print axioms DerridaRetaux.densityR_weightedSup_bound_of_component_bounds
#print axioms DerridaRetaux.sub_shiftLeft_iterate_eq_shiftLeftPartialSum
#print axioms DerridaRetaux.weightedSupThree_sub_shiftLeft_iterate
#print axioms DerridaRetaux.weightedSupThree_discreteDerivative

#print axioms DerridaRetaux.transportDefect_factor
#print axioms DerridaRetaux.transportDefect_le_quadratic
#print axioms DerridaRetaux.weightedL1Three_conv_le
#print axioms DerridaRetaux.weightedSupThree_shiftByInt_nat
#print axioms DerridaRetaux.weightedSupThree_shiftLeft_iterate_gain
#print axioms DerridaRetaux.weightedL1Three_convPow_le_pow
#print axioms DerridaRetaux.weightedSupThree_convPow_succ_le
#print axioms DerridaRetaux.weightedConvolutionPowers_orbit_bounds
#print axioms DerridaRetaux.convolutionNorms_orbit_of_pointwise

#print axioms DerridaRetaux.shiftByInt_of_le
#print axioms DerridaRetaux.shiftByInt_support
#print axioms DerridaRetaux.orbitPositiveTilt_eq_product_shift_arrival
#print axioms DerridaRetaux.arrivalCoeff_succ_eq_formulaSource
#print axioms DerridaRetaux.arrivalCoeff_duhamel
#print axioms DerridaRetaux.arrivalFormulaSource_eq_zero_of_lt
#print axioms DerridaRetaux.arrivalKappa_succ
#print axioms DerridaRetaux.initialArrivalU24_tendsto_zero

#print axioms DerridaRetaux.hasRightEnd_noRightBoundaryAmbiguity
#print axioms DerridaRetaux.isEntranceType_locallyFiniteBelow

#print axioms DerridaRetaux.Audit.deterministicCriticalClassification_without_arity_is_false

#print axioms DerridaRetaux.conv_assoc
#print axioms DerridaRetaux.drStepSeq_hasSum_one

#print axioms DerridaRetaux.orbit_eq_coefficientOrbit
#print axioms DerridaRetaux.lawStep_eq_drStepProb_toPMF

#print axioms DerridaRetaux.criticalProduct_succ
#print axioms DerridaRetaux.criticalProductInclusive_eq

#print axioms DerridaRetaux.volterraSmokeString_isEntranceType
#print axioms DerridaRetaux.volterraSmokeString_hasSecondEntranceMoment
#print axioms DerridaRetaux.volterraSmokeSolution_satisfies
#print axioms DerridaRetaux.volterraSmokeSolution_nonconstant
#print axioms DerridaRetaux.volterraSmokeIntegral_nonzero

#print axioms DerridaRetaux.orbit_two_diracMass_one
#print axioms DerridaRetaux.zeroOneCriticalLaw_critical
#print axioms DerridaRetaux.zeroOneCriticalLaw_not_isDirac

#print axioms DerridaRetaux.powerScale_convPow_hasSum
#print axioms DerridaRetaux.generatingFunction_drStep_cross

#print axioms DerridaRetaux.critical_drStep
#print axioms DerridaRetaux.orbit_critical

#print axioms DerridaRetaux.convPow_zeroAtom_add_apply
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_succ
#print axioms DerridaRetaux.positiveTiltedDensity_drStepProb_two

#print axioms DerridaRetaux.thirdMomentScale_conv
#print axioms DerridaRetaux.orbit_tiltSummable_three

#print axioms DerridaRetaux.tiltedPartition_one_le_of_critical
#print axioms DerridaRetaux.criticalProduct_pos_of_critical

#print axioms DerridaRetaux.normalizedTilt_hasSum
#print axioms DerridaRetaux.normalizedTilt_mean
#print axioms DerridaRetaux.positiveTiltedDensity_shiftedMean_hasSum

#print axioms DerridaRetaux.tiltedPartition_orbit_succ_eq
#print axioms DerridaRetaux.normalizedTilt_orbit_succ_coeff
#print axioms DerridaRetaux.normalizedTiltGeneratingFunction_orbit_succ_cross

#print axioms DerridaRetaux.binary_zero_atom_hasSum
#print axioms DerridaRetaux.orbit_zeroTilt_pos

#print axioms DerridaRetaux.one_sub_transportCoeff_eq
#print axioms DerridaRetaux.one_subCoeff_le_quadratic
#print axioms DerridaRetaux.transportProduct_pos
#print axioms DerridaRetaux.transportProductLimit_pos_of_defect_summable
#print axioms DerridaRetaux.transportCoeff_inverse_uniform

#print axioms DerridaRetaux.survival_eq_one_sub_zero
#print axioms DerridaRetaux.excess_nonneg
#print axioms DerridaRetaux.survival_le_excess_div
#print axioms DerridaRetaux.positiveTiltMass_eq_excess_add_survival_div

#print axioms DerridaRetaux.survival_eq_partition_mul_readout
#print axioms DerridaRetaux.atom_eq_partition_mul_rho
#print axioms DerridaRetaux.excess_orbit_decrement
#print axioms DerridaRetaux.one_add_pow_sub_linear_eq_sq_mul_excessPowerCoeff
#print axioms DerridaRetaux.decrement_tendsto_of_exact_identity
#print axioms DerridaRetaux.excess_orbit_decrement_tendsto
#print axioms DerridaRetaux.integratedLaplaceSecondGap_eq
#print axioms DerridaRetaux.integratedExpThirdRemainder_le_cutoff
#print axioms DerridaRetaux.abs_normalizedIntegratedExpThirdRemainder_le_sqrt
#print axioms DerridaRetaux.integratedLaplaceSecondGap_pos
#print axioms DerridaRetaux.positiveHalfLineMoment_A3_lower
#print axioms DerridaRetaux.positiveHalfLineMoment_zero_and_three_pos
#print axioms DerridaRetaux.deriv_momentLaplaceGap_eq
#print axioms DerridaRetaux.gridBilinearInterp_family_uniformlyBoundedOn_rectangle
#print axioms DerridaRetaux.gridBilinearInterp_family_equicontinuousOn_of_eventually
#print axioms DerridaRetaux.weightedSupThree_log_modulus_of_early_late
#print axioms DerridaRetaux.weightedSupThree_gradient_of_early_late
#print axioms DerridaRetaux.densityInitialSegment_weightedSup_bound
#print axioms DerridaRetaux.densityQuadraticSegment_derivative_weightedSup_log_bound
#print axioms DerridaRetaux.densityLateSegment_derivative_weightedSup_log_bound
#print axioms DerridaRetaux.truncatedSmoothingSplit_of_H1
#print axioms DerridaRetaux.positiveTiltedDensity_spatialSmoothing_of_H1
#print axioms DerridaRetaux.positiveTiltedDensity_temporalTransport_of_bounds
#print axioms DerridaRetaux.positiveTiltedDensity_temporalModulus_of_H1_and_spatial
#print axioms DerridaRetaux.exists_gridBilinearInterp_diagonal_subsequence
#print axioms DerridaRetaux.gridNodeReadout_tendsto_of_uniformOn_exhaustion
#print axioms DerridaRetaux.orbitScaledGrid_adjacent_le_of_gradient
#print axioms DerridaRetaux.exists_orbitScaledGrid_diagonal_subsequence_and_readout
#print axioms DerridaRetaux.transportBetween_eq_transportProduct_div
#print axioms DerridaRetaux.positiveTiltedDensity_eq_transportRatio_add_quadratic_add_higher
#print axioms DerridaRetaux.discreteDerivative_densityQuadraticSegment_telescope
#print axioms DerridaRetaux.densityNonlinearSource_orbit_le_of_weightedL1
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_add_le_shift_add_majorant
#print axioms DerridaRetaux.positiveTiltedDensity_pointwise_of_arrival_far

#print axioms DerridaRetaux.translate_eq_with_common_rightEnd_imp_zero
#print axioms DerridaRetaux.translate_eq_with_common_rightEnd_imp_original_eq
#print axioms DerridaRetaux.cumulative_translate_eq_with_common_rightEnd_imp_zero
#print axioms DerridaRetaux.kotaniCharacteristicFact_imp_cumulative_eq

#print axioms DerridaRetaux.stringY
#print axioms DerridaRetaux.hasDerivAt_stringY
#print axioms DerridaRetaux.hasDerivAt_stringA2Y
#print axioms DerridaRetaux.stringXi_eq_neg_integral_Ioi
#print axioms DerridaRetaux.stringXi_bijOn
#print axioms DerridaRetaux.stringXiMassCoordinate_comp_eq
#print axioms DerridaRetaux.hasDerivAt_stringXiMassCoordinate
#print axioms DerridaRetaux.stringA2Y_two_sided
#print axioms DerridaRetaux.stringXiMassCoordinate_two_sided
#print axioms DerridaRetaux.stringDensityCoefficient_vs_coordinate

#print axioms DerridaRetaux.normalizedCubicMoment_drStep
#print axioms DerridaRetaux.normalizedCubicMoment_orbit_eq
#print axioms DerridaRetaux.normalizedCubicMoment_eqJ
#print axioms DerridaRetaux.normalizedTilt_lowMoments_orbit
#print axioms DerridaRetaux.finiteThirdMoment_implies_cubic_tail_limits
#print axioms DerridaRetaux.weightedL1Three_positiveTiltedDensity_le
#print axioms DerridaRetaux.positiveTiltedDensity_firstShifted_tsum
#print axioms DerridaRetaux.positiveTiltedDensity_weightedMass_orbit
#print axioms DerridaRetaux.orbitTransportDefect_summable
#print axioms DerridaRetaux.transportProduct_tendsto_pos
#print axioms DerridaRetaux.transportProduct_mul_zeroTilt_le_orbitZeroTilt
#print axioms DerridaRetaux.orbitZeroTilt_inverse_uniform
#print axioms DerridaRetaux.quadraticDensityAt_lipschitz_on_unit
#print axioms DerridaRetaux.coefficientVariation_orbit_of_H1a_and_pointwise
#print axioms DerridaRetaux.firstTiltedAtom_eq_theta_sub_theta_succ_add
#print axioms DerridaRetaux.firstTiltedAtomTail_bound_all
#print axioms DerridaRetaux.firstTiltedAtom_squareWeight_sum_eq
#print axioms DerridaRetaux.firstTiltedAtom_squareWeight_sum_linear_bound
#print axioms DerridaRetaux.arrivalInitialIndex_injective
#print axioms DerridaRetaux.sum_range_sum_range_triangle
#print axioms DerridaRetaux.arrivalInitialBlock_le_coefficientTail_of_cubic
#print axioms DerridaRetaux.shiftedCubicMoment_convPow_summable_and_le
#print axioms DerridaRetaux.coefficientTail_le_shiftedCubicMoment_div
#print axioms DerridaRetaux.arrivalMomentTail_bounds
#print axioms DerridaRetaux.SourceMonomialTag.valid_branch_trichotomy
#print axioms DerridaRetaux.SourceMonomialTag.tailThreshold_twice_gt
#print axioms DerridaRetaux.arrivalFormulaSource_sub_eq_fullyExpanded
#print axioms DerridaRetaux.actual_sourceDifference_terms_have_valid_tags
#print axioms DerridaRetaux.sourceFactorValue_eq_coreNormalForm
#print axioms DerridaRetaux.sourceFunctionExpandedTerm_eq_tagNormalForm
#print axioms DerridaRetaux.actual_sourceDifference_terms_have_valid_normalForms
#print axioms DerridaRetaux.sourceShiftChange_eq_zero_of_degree_two

#print axioms DerridaRetaux.cubicSizeBiasedLaw
#print axioms DerridaRetaux.cubicSpineKernel_two_one
#print axioms DerridaRetaux.cubicSizeBiasedPMF_bind_cubicSpineKernel
#print axioms DerridaRetaux.spineMarginalPMF_bind_spineKernel
#print axioms DerridaRetaux.cubicSpineExpectedPositiveIncrement_eq_ratio
#print axioms DerridaRetaux.cubicSpineExpectedPositiveIncrement_le_four
#print axioms DerridaRetaux.spinePathPMF_initial_marginal
#print axioms DerridaRetaux.spinePathPMF_terminal_marginal
#print axioms DerridaRetaux.spinePath_positiveVariation_hasSum
#print axioms DerridaRetaux.spinePathExpectedPositiveVariation_le_four_mul
#print axioms DerridaRetaux.spineSharpTail_le_initial_add
#print axioms DerridaRetaux.profileThirdTail_quadratic_of_concreteSpine
#print axioms DerridaRetaux.profileThirdTail_uniform_integrability_of_concreteSpine
#print axioms DerridaRetaux.FixedArity.cubicWeightedChain
#print axioms DerridaRetaux.FixedArity.thirdMomentTail
#print axioms DerridaRetaux.spineMarginal_eq_zero_of_carrier_eq_zero
#print axioms DerridaRetaux.cubicAllocation_hasSum
#print axioms DerridaRetaux.cubicAllocationWeight_hasSum_one
#print axioms DerridaRetaux.cubicAllocation_carrier_identity
#print axioms DerridaRetaux.cubicSpineOutputMass_eq_nextSizeBiased
#print axioms DerridaRetaux.normalizedFactorialTwo_sq_le
#print axioms DerridaRetaux.criticalSpineIncrementRatio_le_four
#print axioms DerridaRetaux.weightedPathTail_le_initial_add
#print axioms DerridaRetaux.profileThirdTail_quadratic_of_spineTail
#print axioms DerridaRetaux.profileThirdTail_uniform_integrability_of_spineTail
#print axioms DerridaRetaux.sharpnessPowerLaw_critical
#print axioms DerridaRetaux.sharpnessPowerLaw_not_tiltSummable_three
#print axioms DerridaRetaux.sharpnessCriticalInitialData
#print axioms DerridaRetaux.sharpnessPowerLaw_stableProduct_parameters
#print axioms DerridaRetaux.sharpnessPowerLaw_product_bounds
#print axioms DerridaRetaux.no_eventual_subquadratic_poweredPrefixProduct_bound
#print axioms DerridaRetaux.summable_partition_excess_sq
#print axioms DerridaRetaux.partition_log_sum_div_log_tendsto
#print axioms DerridaRetaux.orbit_criticalProduct_sub_two_log_isLittleO
#print axioms DerridaRetaux.sharpnessPowerLaw_not_partition_excess_limit
#print axioms DerridaRetaux.exists_critical_law_with_finite_real_tilt_and_no_profile_excess_limit
#print axioms DerridaRetaux.FixedArity.sharpness_core
#print axioms DerridaRetaux.FixedArity.sharpness
#print axioms DerridaRetaux.FixedArity.cubicMoment
#print axioms DerridaRetaux.FixedArity.firstTiltedAtomTail
#print axioms DerridaRetaux.FixedArity.arrivalRecursion

#print axioms DerridaRetaux.arrivalFormulaSource_sub_tailControlled_of_H1
#print axioms DerridaRetaux.arrivalFormulaSource_sub_tail_bound_of_H1
#print axioms DerridaRetaux.arrivalCoeff_far_bound_of_H1
#print axioms DerridaRetaux.arrivalCoeff_scaled_far_constant_of_H1
#print axioms DerridaRetaux.positiveTiltedDensity_pointwise_of_H1
#print axioms DerridaRetaux.FixedArity.sourceDifference
#print axioms DerridaRetaux.FixedArity.farArrivalBound
#print axioms DerridaRetaux.FixedArity.pointwiseBound
#print axioms DerridaRetaux.FixedArity.smoothingTwoParameter
#print axioms DerridaRetaux.FixedArity.smoothing

#print axioms DerridaRetaux.profileDensityMomentTail_uniform_integrability_of_spineTail
#print axioms DerridaRetaux.scaledDiscreteMoment_tendsto_of_heads_and_uniform_tails_along
#print axioms DerridaRetaux.profileDensityMoment_tendsto_of_compact_heads_and_spineTail_along
#print axioms DerridaRetaux.integral_cubicTail_le_of_finiteMeasure_tendsto_eventually
#print axioms DerridaRetaux.integral_cubicTail_scaledLatticeMeasure_eq_all
#print axioms DerridaRetaux.limit_cubicTail_le_of_scaledLatticeMeasuresAlong_tendsto_eventually
#print axioms DerridaRetaux.finiteMeasure_tendsto_of_compact_integrals_and_mass
#print axioms DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_of_compact_sums_and_mass
#print axioms DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_finiteDensityMeasure
#print axioms DerridaRetaux.latticeLeftRiemannSum_tendsto_intervalIntegral
#print axioms DerridaRetaux.compact_lattice_sums_tendsto_of_locallyUniform
#print axioms DerridaRetaux.continuousOn_gluedExhaustionTimeOneSlice_Ici
#print axioms DerridaRetaux.locallyUniformLatticeDensity_of_orbitScaledGrid_exhaustionLimits
#print axioms DerridaRetaux.gluedExhaustionTimeOneSlice_nonneg_of_exhaustionLimits
#print axioms DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_finiteDensityMeasure_of_locallyUniform
#print axioms DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_of_exhaustionLimits
#print axioms DerridaRetaux.scaled_conv_eq_lattice_product_sum
#print axioms DerridaRetaux.latticeSelfConvolutionSum_tendsto_moving
#print axioms DerridaRetaux.scaled_conv_tendsto_moving_of_locallyUniform
#print axioms DerridaRetaux.scaled_conv_gridIndex_tendsto_of_locallyUniform_of_nonneg
#print axioms DerridaRetaux.shiftRightPow_apply_eq_ite
#print axioms DerridaRetaux.scaled_shiftRightPow_conv_gridIndex_tendsto_of_nonneg
#print axioms DerridaRetaux.scaled_conv_uniform_on_compact_away_zero_of_locallyUniform
#print axioms DerridaRetaux.orbit_rho_scaled_conv_uniform_on_compact_away_zero

#print axioms DerridaRetaux.positiveTiltedDensity_orbit_succ_fullRhoSource
#print axioms DerridaRetaux.seq_recurrence_apply_eq_transport_add_forcing
#print axioms DerridaRetaux.positiveTiltedDensity_orbit_apply_eq_discreteMildDuhamel
#print axioms DerridaRetaux.densityHigherSegment_supLE_of_order_four
#print axioms DerridaRetaux.densityHigherSegment_scaled_abs_le_const_div
#print axioms DerridaRetaux.densityHigherSegment_scaled_tendsto_zero_of_order_four_on_annulus
#print axioms DerridaRetaux.densityHigherSegment_orbit_scaled_tendsto_zero_on_annulus
#print axioms DerridaRetaux.hasIntegralDerivativeOn_of_tendstoUniformly_of_tendstoInL1On
#print axioms DerridaRetaux.hasIntegralDerivativeOn_Icc_of_local_uniform_and_L1
#print axioms DerridaRetaux.HasIntegralDerivativeOn.hasDerivAt_of_continuousOn_Icc
#print axioms DerridaRetaux.HasIntegralDerivativeOn.contDiffOn_Ioo_of_continuousOn_Icc
#print axioms DerridaRetaux.natFloor_window_div_cofinal_tendsto
#print axioms DerridaRetaux.orbit_densityD_natFloor_tendsto_half_of_H1a
#print axioms DerridaRetaux.orbit_densityD_uniform_after_natFloor_of_H1a
#print axioms DerridaRetaux.transportBetween_orbit_tendsto_one_along_of_H1a
#print axioms DerridaRetaux.transportBetween_orbit_uniform_on_natFloor_window_of_H1a
#print axioms DerridaRetaux.terminalTransportWeight_orbit_natFloor_window_uniform_of_H1a
#print axioms DerridaRetaux.gridTimeArraySum_tendsto_of_uniform_approximation_on_Ioi
#print axioms DerridaRetaux.hasTimeIntegratedWeakEquationOn_of_pointwise_derivative
#print axioms DerridaRetaux.hasWeakEquationOn_of_pointwise_weak_derivatives
#print axioms DerridaRetaux.hasIntegralDerivativeOn_weakObservable_of_integratedWeakEquation
#print axioms DerridaRetaux.hasTimeIntegratedWeakEquationOn_iff_hasIntegralDerivativeOn

#print axioms DerridaRetaux.locallyUniformLatticeDensity_of_eventually
#print axioms DerridaRetaux.locallyUniformLatticeDensity_of_eventually_epsilon
#print axioms DerridaRetaux.locallyUniformLatticeDensity_of_gluedExhaustion_at_time
#print axioms DerridaRetaux.locallyUniformLatticeDensity_orbit_of_gluedExhaustion_at_time
#print axioms DerridaRetaux.orbit_rho_scaled_conv_tendsto_of_gluedExhaustion_at_time
#print axioms DerridaRetaux.locallyUniformSpacetimeLatticeDensity_orbit_of_gluedExhaustion

#print axioms DerridaRetaux.continuousOn_gluedExhaustionLimit_rectangle
#print axioms DerridaRetaux.tendstoUniformlyOn_gluedExhaustionLimit

#print axioms DerridaRetaux.scaled_conv_shifted_floor_window_uniform
#print axioms DerridaRetaux.densityQuadraticWeight_natFloor_window_uniform_of_H1a
#print axioms DerridaRetaux.quadraticDuhamelGridSum_tendsto_of_H1a
#print axioms DerridaRetaux.scaled_densityQuadraticSegment_tendsto_of_H1a
#print axioms DerridaRetaux.scaled_densityInitialSegment_tendsto_of_H1a
#print axioms DerridaRetaux.scaled_densityHigherSegment_floor_tendsto_zero
#print axioms DerridaRetaux.scaled_terminalDensity_tendsto
#print axioms DerridaRetaux.continuousOn_shiftedConvolutionTimeIntegral
#print axioms DerridaRetaux.gluedExhaustionLimit_mild_pos_of_H1a
#print axioms DerridaRetaux.gluedExhaustionLimit_mild_zero_of_H1a
#print axioms DerridaRetaux.gluedExhaustionLimit_mild_of_H1a

#print axioms DerridaRetaux.constructed_stringCumulative_of_neg
#print axioms DerridaRetaux.tendsto_constructed_stringCumulative_nhds_top
#print axioms DerridaRetaux.constructedEntranceString_isEntranceType
#print axioms DerridaRetaux.constructedEntranceString_hasSecondEntranceMoment
#print axioms DerridaRetaux.constructedEntranceString_correctRightEnd
#print axioms DerridaRetaux.constructedEntranceString_hasRightEnd_zero
#print axioms DerridaRetaux.constructedPhi_pos
#print axioms DerridaRetaux.tendsto_timeOfNegativeCoordinate_atBot_nhdsGT_zero
#print axioms DerridaRetaux.tendsto_constructedEndpointSolution_add_id_atBot
#print axioms DerridaRetaux.hasDerivAt_constructedEndpointSolution_of_neg
#print axioms DerridaRetaux.hasDerivAt_constructedEndpointSlope_of_neg
#print axioms DerridaRetaux.tendsto_constructedEndpointSlope_atBot
#print axioms DerridaRetaux.hasSingularCharacteristic_of_endpoint_representation
#print axioms DerridaRetaux.constructedEndpointAtTime_pos
#print axioms DerridaRetaux.constructedEndpointSolution_pos_of_neg
#print axioms DerridaRetaux.strictAntiOn_constructedEndpointSolution
#print axioms DerridaRetaux.hasDerivAt_constructedPhi
#print axioms DerridaRetaux.hasDerivAt_constructedEndpointAtTime
#print axioms DerridaRetaux.constructedEndpointAtTime_le_Y_mul_A2
#print axioms DerridaRetaux.tendsto_constructedEndpointAtTime_atTop_zero
#print axioms DerridaRetaux.tendsto_timeOfNegativeCoordinate_orderIso_nhdsLT_zero_atTop
#print axioms DerridaRetaux.tendsto_constructedEndpointSolution_nhdsLT_zero
#print axioms DerridaRetaux.hasDerivAt_constructedEndpointSolution_at
#print axioms DerridaRetaux.hasDerivAt_constructedEndpointSlope_at
#print axioms DerridaRetaux.constructedEndpointAtTime_add_coordinate_eq
#print axioms DerridaRetaux.tendsto_constructedEndpoint_add_coordinate_at_zero
#print axioms DerridaRetaux.model_stringCumulative_of_neg
#print axioms DerridaRetaux.tendsto_model_stringCumulative_nhdsLT_zero_top
#print axioms DerridaRetaux.modelEntranceString_isEntranceType
#print axioms DerridaRetaux.modelEntranceString_hasSecondEntranceMoment
#print axioms DerridaRetaux.modelEntranceString_correctRightEnd
#print axioms DerridaRetaux.modelEntranceString_hasRightEnd_zero
#print axioms DerridaRetaux.modelStringEntranceSolution_isVolterra
#print axioms DerridaRetaux.modelEntranceString_hasSingularCharacteristic
#print axioms DerridaRetaux.sourceModelEntranceString_hasSingularCharacteristic
#print axioms DerridaRetaux.modelStringEndpointSolution_pos
#print axioms DerridaRetaux.modelStringEndpointSolutionDeriv_neg
#print axioms DerridaRetaux.strictAntiOn_modelStringEndpointSolution
#print axioms DerridaRetaux.modelStringEndpointSolution_ode
#print axioms DerridaRetaux.modelStringEndpointSolution_secondODE
#print axioms DerridaRetaux.tendsto_modelStringEndpointSolutionDeriv_atBot
#print axioms DerridaRetaux.tendsto_modelStringEndpointSolution_nhdsLT_zero
#print axioms DerridaRetaux.tendsto_modelStringEndpointSolution_add_id_atBot
#print axioms DerridaRetaux.physicalTimeCoordinate_eq_neg_div
#print axioms DerridaRetaux.physicalTimeScale_eq
#print axioms DerridaRetaux.physicalTimeZerothMoment_eq
#print axioms DerridaRetaux.physicalTimePhi_eq_of_modelDerivative
#print axioms DerridaRetaux.hasDerivAt_physicalTimePhi
#print axioms DerridaRetaux.physicalTimeLaplaceGap_eq
#print axioms DerridaRetaux.physicalTimeLaplaceTransform_eq

#print axioms DerridaRetaux.integrableOn_pow_mul_of_locallyUniform_and_momentBound_Ici
#print axioms DerridaRetaux.orbit_scaledDiscreteMoment_eventually_bounded_of_weightedL1
#print axioms DerridaRetaux.softScaledDiscreteMoment_sandwich
#print axioms DerridaRetaux.scaledDiscreteMoment_tendsto_of_locallyUniform_and_uniformTails
#print axioms DerridaRetaux.orbit_scaledDiscreteMoment_le_envelope
#print axioms DerridaRetaux.scaledLatticeMeasuresAlong_tendsto_of_locallyUniform_and_mass
#print axioms DerridaRetaux.FixedArity.subsequentialMildEquation
#print axioms DerridaRetaux.FixedArity.subsequentialMoment_integrable
#print axioms DerridaRetaux.FixedArity.subsequentialMoment_tendsto
#print axioms DerridaRetaux.FixedArity.subsequentialMoment_bounds
#print axioms DerridaRetaux.FixedArity.subsequentialThirdMomentTail
