#!/usr/bin/env python3
"""Build and audit the current edition; fail before publishing any success result."""
import argparse
import csv
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
STANDARD = {"propext", "Classical.choice", "Quot.sound"}
TAGS = {
    "DerridaRetaux.HumanInputs.cdhls_excess_upper": "H1a",
    "DerridaRetaux.HumanInputs.cdhls_product_upper": "H1b",
    "DerridaRetaux.HumanInputs.kotani_characteristic_eq_implies_translate": "H2",
    "DerridaRetaux.HumanInputs.chenShi_stable_product": "H3",
}
PUBLIC = {
    "DerridaRetaux.FixedArity.profile": {"H1a", "H1b", "H2"},
    "DerridaRetaux.FixedArity.sharpnessSurvival": {"H3"},
    "DerridaRetaux.FixedArity.productAsymptoticOfSurvival": set(),
    "DerridaRetaux.excess_tendsto_of_survival_asymptotic": set(),
    "DerridaRetaux.FixedArity.cubicWeightedInfiniteChain": set(),
    "DerridaRetaux.FixedArity.momentLaplaceLocalIntegralDerivatives": {"H1a", "H1b"},
    "DerridaRetaux.FixedArity.farArrivalBoundUniform": {"H1a", "H1b"},
    "DerridaRetaux.FixedArity.tiltedLawRecursion": set(),
    "DerridaRetaux.FixedArity.weightedMass": {"H1a", "H1b"},
    "DerridaRetaux.FixedArity.arrivalMomentTail": {"H1a", "H1b"},
}


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(args, log):
    print("RUN", " ".join(map(str, args)), flush=True)
    with log.open("w") as output:
        result = subprocess.run(args, cwd=ROOT, stdout=output, stderr=subprocess.STDOUT)
    if result.returncode:
        print(log.read_text()[-12000:], file=sys.stderr)
        raise RuntimeError(f"exit {result.returncode}: {args}; see {log}")
    print("PASSED", log.name, flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--lake", default=shutil.which("lake") or str(Path.home() / ".elan/bin/lake"))
    parser.add_argument("--output", default="validation/2026-09-29")
    args = parser.parse_args()
    out = ROOT / args.output
    out.mkdir(parents=True, exist_ok=True)
    # A fresh invocation invalidates an earlier success marker before doing work.
    marker = out / "verification-result.json"
    marker.write_text(json.dumps({"status": "RUNNING"}, indent=2) + "\n")
    ledger_paths = [ROOT / (name + "_LEDGER.csv")
                    for name in ("STATEMENT", "EQUATION", "UNNUMBERED")]
    rows = {p: list(csv.DictReader(p.open())) for p in ledger_paths}
    source_decls = {d.strip() for rs in rows.values() for row in rs
                    for d in row["lean_name"].split(";") if d.strip()}
    extended = set()
    for name in ("PrintAxioms", "StatementCompletion", "SourceWrappers", "MildSourceDecls", "HumanInputs"):
        text = (ROOT / f"DerridaRetaux/Audit/{name}.lean").read_text()
        extended.update(re.findall(r"^#print axioms (\S+)\s*$", text, re.M))
    declarations = sorted(source_decls | extended | set(PUBLIC))
    audit = ROOT / "DerridaRetaux/Audit/CurrentRevision.lean"
    audit.write_text(
        "import DerridaRetaux\nimport DerridaRetaux.Audit.ArchitectureCounterexample\n\n"
        "/-! Generated by scripts/verify_all.py: current and extended dependency audit. -/\n\n"
        "set_option pp.universes true\n\n" +
        "\n".join(f"#check {d}\n#print axioms {d}" for d in declarations) + "\n")
    sources = [ROOT / "DerridaRetaux.lean", *sorted((ROOT / "DerridaRetaux").rglob("*.lean")),
               ROOT / "DR_Yaglom.tex", ROOT / "lean-toolchain", ROOT / "lake-manifest.json",
               ROOT / "lakefile.toml", ROOT / "revision-manifest.json"]
    before = {str(p.relative_to(ROOT)): digest(p) for p in sources}
    run([args.lake, "build"], out / "build.log")
    run([args.lake, "build", "DerridaRetaux.Audit.ArchitectureCounterexample"],
        out / "audit-dependency-build.log")
    run([args.lake, "env", "lean", str(audit.relative_to(ROOT))], out / "compiled-axioms.log")
    assert before == {str(p.relative_to(ROOT)): digest(p) for p in sources}, \
        "Sources changed during verification; rerun the audit."
    log = (out / "compiled-axioms.log").read_text()
    axioms = {}
    for match in re.finditer(r"'([^\n]+?)' depends on axioms:\s*\[([^\]]*)\]", log, re.S):
        axioms[match[1]] = {a.strip() for a in match[2].split(",") if a.strip()}
    for match in re.finditer(r"'([^\n]+?)' does not depend on any axioms", log):
        axioms[match[1]] = set()
    assert set(axioms) == set(declarations), ("audit declaration mismatch",
                                            set(declarations) - set(axioms))
    for name, deps in axioms.items():
        assert deps <= STANDARD | set(TAGS), (name, "unapproved axiom", deps)
    for name in TAGS:
        assert axioms[name] == {name}, (name, "published input has unexpected dependencies")
    for name, expected in PUBLIC.items():
        actual = {TAGS[a] for a in axioms[name] - STANDARD}
        assert actual == expected, (name, expected, actual)
    for p, rs in rows.items():
        for row in rs:
            ds = [d.strip() for d in row["lean_name"].split(";") if d.strip()]
            custom = {d: sorted(axioms[d] - STANDARD) for d in ds}
            row["compiled_declaration_custom_axioms"] = json.dumps(custom, sort_keys=True)
            tags = {TAGS[a] for deps in custom.values() for a in deps}
            # Retain source-level inputs for core lemmas that take those facts as hypotheses.
            prior = {t.strip() for t in row["transitive_human_inputs"].split(";")
                     if t.strip() and t.strip() != "none"}
            assert prior <= set(TAGS.values()), (p, prior)
            row["transitive_human_inputs"] = ";".join(sorted(prior | tags)) or "none"
            if "expected_inputs" in row:
                row["expected_inputs"] = row["transitive_human_inputs"]
        with p.open("w", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rs[0]), quoting=csv.QUOTE_ALL)
            writer.writeheader()
            writer.writerows(rs)
    run([sys.executable, "scripts/verify_revision.py"], out / "source-and-ledger-check.log")
    result = {
        "status": "COMPILED_AND_AXIOMS_CHECKED",
        "ledger_declarations": len(source_decls),
        "extended_declarations": len(extended),
        "unique_audited_declarations": len(declarations),
        "public_theorem_custom_axioms": {
            d: sorted(axioms[d] - STANDARD) for d in PUBLIC},
        "sources_sha256": before,
        "ledger_sha256": {p.name: digest(p) for p in ledger_paths},
        "logs_sha256": {p.name: digest(p) for p in out.glob("*.log")
                        if p.name != "baseline-build.log"},
    }
    marker.write_text(json.dumps(result, indent=2) + "\n")
    print("VERIFIED", len(source_decls), "source declarations;",
          len(declarations), "unique audited declarations", flush=True)


if __name__ == "__main__":
    main()
